(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32-34-37-38"]
open Array
module Ortac_runtime = Ortac_runtime_qcheck_stm_sequential
module SUT =
  (Ortac_runtime.SUT.Make)(struct
                             type sut = char t
                             let init () = make 16 'a'
                           end)
module ModelElt =
  struct
    type nonrec elt =
      {
      size: Ortac_runtime.integer ;
      contents: char Ortac_runtime.Gospelstdlib.sequence }
    let init =
      let i_2 = 16
      and a_2 = 'a' in
      {
        size =
          (try Ortac_runtime.Gospelstdlib.integer_of_int i_2
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "array.mli";
                            pos_lnum = 23;
                            pos_bol = 862;
                            pos_cnum = 883
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "array.mli";
                            pos_lnum = 23;
                            pos_bol = 862;
                            pos_cnum = 884
                          }
                      })));
        contents =
          (try
             Ortac_runtime.Gospelstdlib.Sequence.init
               (Ortac_runtime.Gospelstdlib.integer_of_int i_2) (fun j -> a_2)
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "array.mli";
                            pos_lnum = 24;
                            pos_bol = 885;
                            pos_cnum = 910
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "array.mli";
                            pos_lnum = 24;
                            pos_bol = 885;
                            pos_cnum = 938
                          }
                      })))
      }
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    module QCheck =
      struct
        include QCheck
        module Gen = struct include Gen
                            let int = nat_small end
      end
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type _ ty +=  
      | SUT: SUT.elt ty 
    let sut = (SUT, (fun _ -> "<sut>"))
    type sut = SUT.t
    let init_sut = SUT.create 2
    type state = Model.t
    let init_state = Model.create 2 ()
    type raw_cmd =
      | Length 
      | Get of int 
      | Set of int * char 
      | Make of int * char 
      | Append 
      | Sub of int * int 
      | Copy 
      | Fill of int * int * char 
      | To_list 
      | Of_list of char list 
      | Mem of char 
      | For_all of (char -> bool) QCheck.fun_ 
    type flag =
      | Seq 
      | Dom 
    type cmd = {
      flag: flag ;
      raw_cmd: raw_cmd }
    let with_flag flag raw_cmd = { flag; raw_cmd }
    let show_cmd cmd__005_ =
      match cmd__005_.raw_cmd with
      | Length -> Format.asprintf "%s <sut>" "length"
      | Get i ->
          Format.asprintf "protect (fun () -> %s <sut> %a)" "get"
            (Util.Pp.pp_int true) i
      | Set (i_1, a_1) ->
          Format.asprintf "protect (fun () -> %s <sut> %a %a)" "set"
            (Util.Pp.pp_int true) i_1 (Util.Pp.pp_char true) a_1
      | Make (i_2, a_2) ->
          Format.asprintf "protect (fun () -> %s %a %a)" "make"
            (Util.Pp.pp_int true) i_2 (Util.Pp.pp_char true) a_2
      | Append -> Format.asprintf "%s <sut> <sut>" "append"
      | Sub (i_3, n) ->
          Format.asprintf "protect (fun () -> %s <sut> %a %a)" "sub"
            (Util.Pp.pp_int true) i_3 (Util.Pp.pp_int true) n
      | Copy -> Format.asprintf "%s <sut>" "copy"
      | Fill (pos, len, x) ->
          Format.asprintf "protect (fun () -> %s <sut> %a %a %a)" "fill"
            (Util.Pp.pp_int true) pos (Util.Pp.pp_int true) len
            (Util.Pp.pp_char true) x
      | To_list -> Format.asprintf "%s <sut>" "to_list"
      | Of_list l ->
          Format.asprintf "%s %a" "of_list"
            (Util.Pp.pp_list Util.Pp.pp_char true) l
      | Mem a_3 ->
          Format.asprintf "%s %a <sut>" "mem" (Util.Pp.pp_char true) a_3
      | For_all p ->
          Format.asprintf "%s %a <sut>" "for_all" (Util.Pp.pp_fun_ true) p
    let cleanup _ = ()
    let gen_cmd _ =
      let open QCheck in
        let open Gen in
          oneof_weighted
            [(1, (pure Length));
            (1, ((pure (fun i -> Get i)) <*> int));
            (1, (((pure (fun i_1 a_1 -> Set (i_1, a_1))) <*> int) <*> char));
            (0,
              (((pure (fun i_2 a_2 -> Make (i_2, a_2))) <*> nat_small) <*>
                 char));
            (1, (pure Append));
            (1, (((pure (fun i_3 n -> Sub (i_3, n))) <*> int) <*> int));
            (1, (pure Copy));
            (1,
              ((((pure (fun pos len x -> Fill (pos, len, x))) <*> int) <*>
                  int)
                 <*> char));
            (1, (pure To_list));
            (1, ((pure (fun l -> Of_list l)) <*> (list char)));
            (1, ((pure (fun a_3 -> Mem a_3)) <*> char));
            (1,
              ((pure (fun p -> For_all p)) <*>
                 (fun1 Observable.char QCheck.bool).gen))]
    let gen_cmd state__125_ =
      let open QCheck in
        let open Gen in (with_flag Seq) <$> (gen_cmd state__125_)
    let arb_cmd state__001_ =
      let open QCheck in make ~print:show_cmd (gen_cmd state__001_)
    let next_state cmd__006_ state__007_ =
      match cmd__006_.raw_cmd with
      | Length ->
          let t_1__008_ = Model.get state__007_ 0 in
          let t_1__009_ = t_1__008_ in
          Model.push (Model.drop_n state__007_ 1) t_1__009_
      | Get i ->
          let t_2__010_ = Model.get state__007_ 0 in
          if
            (try
               let __t1__012_ =
                 Ortac_runtime.Gospelstdlib.(<=)
                   (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i) in
               let __t2__013_ =
                 Ortac_runtime.Gospelstdlib.(<)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i)
                   t_2__010_.size in
               __t1__012_ && __t2__013_
             with | e -> false)
          then
            let t_2__011_ = t_2__010_ in
            Model.push (Model.drop_n state__007_ 1) t_2__011_
          else state__007_
      | Set (i_1, a_1) ->
          let t_3__014_ = Model.get state__007_ 0 in
          if
            (try
               let __t1__016_ =
                 Ortac_runtime.Gospelstdlib.(<=)
                   (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i_1) in
               let __t2__017_ =
                 Ortac_runtime.Gospelstdlib.(<)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                   t_3__014_.size in
               __t1__016_ && __t2__017_
             with | e -> false)
          then
            let t_3__015_ =
              let open ModelElt in
                {
                  t_3__014_ with
                  contents =
                    (try
                       Ortac_runtime.Gospelstdlib.Sequence.set
                         t_3__014_.contents
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_1) a_1
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 18;
                                      pos_bol = 629;
                                      pos_cnum = 654
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 18;
                                      pos_bol = 629;
                                      pos_cnum = 687
                                    }
                                })))
                } in
            Model.push (Model.drop_n state__007_ 1) t_3__015_
          else state__007_
      | Make (i_2, a_2) ->
          if
            (try
               Ortac_runtime.Gospelstdlib.(>=)
                 (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                 (Ortac_runtime.Gospelstdlib.integer_of_int 0)
             with | e -> false)
          then
            let t_4__019_ =
              let open ModelElt in
                {
                  size =
                    (try Ortac_runtime.Gospelstdlib.integer_of_int i_2
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 23;
                                      pos_bol = 862;
                                      pos_cnum = 883
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 23;
                                      pos_bol = 862;
                                      pos_cnum = 884
                                    }
                                })));
                  contents =
                    (try
                       Ortac_runtime.Gospelstdlib.Sequence.init
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                         (fun j -> a_2)
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 24;
                                      pos_bol = 885;
                                      pos_cnum = 910
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 24;
                                      pos_bol = 885;
                                      pos_cnum = 938
                                    }
                                })))
                } in
            (if cmd__006_.flag = Seq
             then Model.push (Model.drop_n state__007_ 0) t_4__019_
             else Model.drop_n state__007_ 0)
          else state__007_
      | Append ->
          let a_4__020_ = Model.get state__007_ 0
          and b__021_ = Model.get state__007_ 1 in
          let t_5__025_ =
            let open ModelElt in
              {
                size =
                  (try
                     Ortac_runtime.Gospelstdlib.(+) a_4__020_.size
                       b__021_.size
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 28;
                                    pos_bol = 1097;
                                    pos_cnum = 1125
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 28;
                                    pos_bol = 1097;
                                    pos_cnum = 1126
                                  }
                              })));
                contents =
                  (try
                     Ortac_runtime.Gospelstdlib.(++) a_4__020_.contents
                       b__021_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 29;
                                    pos_bol = 1134;
                                    pos_cnum = 1170
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 29;
                                    pos_bol = 1134;
                                    pos_cnum = 1172
                                  }
                              })))
              }
          and a_4__024_ = a_4__020_
          and b__023_ = b__021_ in
          if cmd__006_.flag = Seq
          then
            Model.push
              (Model.push (Model.push (Model.drop_n state__007_ 2) b__023_)
                 a_4__024_) t_5__025_
          else
            Model.push (Model.push (Model.drop_n state__007_ 2) b__023_)
              a_4__024_
      | Sub (i_3, n) ->
          let t_6__026_ = Model.get state__007_ 0 in
          if
            (try
               let __t1__030_ =
                 Ortac_runtime.Gospelstdlib.(<=)
                   (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i_3) in
               let __t2__031_ =
                 Ortac_runtime.Gospelstdlib.(<=)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                   (Ortac_runtime.Gospelstdlib.Sequence.length
                      t_6__026_.contents) in
               __t1__030_ && __t2__031_
             with | e -> false) &&
              ((try
                  let __t1__032_ =
                    Ortac_runtime.Gospelstdlib.(<=)
                      (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                      (Ortac_runtime.Gospelstdlib.(+)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                         (Ortac_runtime.Gospelstdlib.integer_of_int n)) in
                  let __t2__033_ =
                    Ortac_runtime.Gospelstdlib.(<=)
                      (Ortac_runtime.Gospelstdlib.(+)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                         (Ortac_runtime.Gospelstdlib.integer_of_int n))
                      (Ortac_runtime.Gospelstdlib.Sequence.length
                         t_6__026_.contents) in
                  __t1__032_ && __t2__033_
                with | e -> false))
          then
            let r__029_ =
              let open ModelElt in
                {
                  size =
                    (try Ortac_runtime.Gospelstdlib.integer_of_int n
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 35;
                                      pos_bol = 1440;
                                      pos_cnum = 1461
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 35;
                                      pos_bol = 1440;
                                      pos_cnum = 1462
                                    }
                                })));
                  contents =
                    (try
                       if
                         (Ortac_runtime.Gospelstdlib.integer_of_int n) =
                           (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                       then Ortac_runtime.Gospelstdlib.Sequence.empty
                       else
                         Ortac_runtime.Gospelstdlib.__mix_Buddub
                           t_6__026_.contents
                           (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                           (Ortac_runtime.Gospelstdlib.(-)
                              (Ortac_runtime.Gospelstdlib.(+)
                                 (Ortac_runtime.Gospelstdlib.integer_of_int
                                    i_3)
                                 (Ortac_runtime.Gospelstdlib.integer_of_int n))
                              (Ortac_runtime.Gospelstdlib.integer_of_int 1))
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 36;
                                      pos_bol = 1463;
                                      pos_cnum = 1488
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 36;
                                      pos_bol = 1463;
                                      pos_cnum = 1542
                                    }
                                })))
                }
            and t_6__028_ = t_6__026_ in
            (if cmd__006_.flag = Seq
             then
               Model.push (Model.push (Model.drop_n state__007_ 1) t_6__028_)
                 r__029_
             else Model.push (Model.drop_n state__007_ 1) t_6__028_)
          else state__007_
      | Copy ->
          let t_7__034_ = Model.get state__007_ 0 in
          let r_1__037_ =
            let open ModelElt in
              {
                size =
                  (try t_7__034_.size
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 40;
                                    pos_bol = 1713;
                                    pos_cnum = 1734
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 40;
                                    pos_bol = 1713;
                                    pos_cnum = 1740
                                  }
                              })));
                contents =
                  (try t_7__034_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 41;
                                    pos_bol = 1741;
                                    pos_cnum = 1766
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 41;
                                    pos_bol = 1741;
                                    pos_cnum = 1776
                                  }
                              })))
              }
          and t_7__036_ = t_7__034_ in
          if cmd__006_.flag = Seq
          then
            Model.push (Model.push (Model.drop_n state__007_ 1) t_7__036_)
              r_1__037_
          else Model.push (Model.drop_n state__007_ 1) t_7__036_
      | Fill (pos, len, x) ->
          let t_8__038_ = Model.get state__007_ 0 in
          if
            (try
               Ortac_runtime.Gospelstdlib.(<=)
                 (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                 (Ortac_runtime.Gospelstdlib.integer_of_int pos)
             with | e -> false) &&
              ((try
                  Ortac_runtime.Gospelstdlib.(<=)
                    (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                    (Ortac_runtime.Gospelstdlib.integer_of_int len)
                with | e -> false) &&
                 ((try
                     Ortac_runtime.Gospelstdlib.(<=)
                       (Ortac_runtime.Gospelstdlib.(+)
                          (Ortac_runtime.Gospelstdlib.integer_of_int pos)
                          (Ortac_runtime.Gospelstdlib.integer_of_int len))
                       t_8__038_.size
                   with | e -> false)))
          then
            let t_8__041_ =
              let open ModelElt in
                {
                  t_8__038_ with
                  contents =
                    (try
                       Ortac_runtime.Gospelstdlib.Sequence.init
                         (Ortac_runtime.Gospelstdlib.Sequence.length
                            t_8__038_.contents)
                         (fun i_4 ->
                            if
                              let __t1__039_ =
                                Ortac_runtime.Gospelstdlib.(<=)
                                  (Ortac_runtime.Gospelstdlib.integer_of_int
                                     pos) i_4 in
                              let __t2__040_ =
                                Ortac_runtime.Gospelstdlib.(<) i_4
                                  (Ortac_runtime.Gospelstdlib.(+)
                                     (Ortac_runtime.Gospelstdlib.integer_of_int
                                        pos)
                                     (Ortac_runtime.Gospelstdlib.integer_of_int
                                        len)) in
                              __t1__039_ && __t2__040_
                            then x
                            else
                              Ortac_runtime.Gospelstdlib.__mix_Bub
                                t_8__038_.contents i_4)
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 49;
                                      pos_bol = 2024;
                                      pos_cnum = 2049
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "array.mli";
                                      pos_lnum = 49;
                                      pos_bol = 2024;
                                      pos_cnum = 2164
                                    }
                                })))
                } in
            Model.push (Model.drop_n state__007_ 1) t_8__041_
          else state__007_
      | To_list ->
          let t_9__042_ = Model.get state__007_ 0 in
          let t_9__043_ = t_9__042_ in
          Model.push (Model.drop_n state__007_ 1) t_9__043_
      | Of_list l ->
          let t_10__045_ =
            let open ModelElt in
              {
                size =
                  (try Ortac_runtime.Gospelstdlib.List.length l
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 57;
                                    pos_bol = 2582;
                                    pos_cnum = 2603
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 57;
                                    pos_bol = 2582;
                                    pos_cnum = 2616
                                  }
                              })));
                contents =
                  (try Ortac_runtime.Gospelstdlib.List.to_seq l
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 58;
                                    pos_bol = 2617;
                                    pos_cnum = 2642
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 58;
                                    pos_bol = 2617;
                                    pos_cnum = 2655
                                  }
                              })))
              } in
          if cmd__006_.flag = Seq
          then Model.push (Model.drop_n state__007_ 0) t_10__045_
          else Model.drop_n state__007_ 0
      | Mem a_3 ->
          let t_11__046_ = Model.get state__007_ 0 in
          let t_11__047_ = t_11__046_ in
          Model.push (Model.drop_n state__007_ 1) t_11__047_
      | For_all p ->
          let t_12__048_ = Model.get state__007_ 0 in
          let t_12__049_ = t_12__048_ in
          Model.push (Model.drop_n state__007_ 1) t_12__049_
    let precond cmd__093_ state__094_ =
      match cmd__093_.raw_cmd with
      | Length -> true
      | Get i -> true
      | Set (i_1, a_1) -> true
      | Make (i_2, a_2) -> true
      | Append -> true
      | Sub (i_3, n) -> true
      | Copy -> true
      | Fill (pos, len, x) -> true
      | To_list -> true
      | Of_list l -> true
      | Mem a_3 -> true
      | For_all p -> true
    let postcond _ _ _ = true
    let run cmd__095_ sut__096_ =
      match cmd__095_.raw_cmd with
      | Length ->
          Res
            (int,
              (let t_1__097_ = SUT.get sut__096_ 0 in
               let res__098_ = length t_1__097_ in res__098_))
      | Get i ->
          Res
            ((result char exn),
              (let t_2__099_ = SUT.get sut__096_ 0 in
               let res__100_ = protect (fun () -> get t_2__099_ i) () in
               res__100_))
      | Set (i_1, a_1) ->
          Res
            ((result unit exn),
              (let t_3__101_ = SUT.get sut__096_ 0 in
               let res__102_ = protect (fun () -> set t_3__101_ i_1 a_1) () in
               res__102_))
      | Make (i_2, a_2) ->
          Res
            ((result sut exn),
              (let res__103_ = protect (fun () -> make i_2 a_2) () in
               ((match res__103_ with
                 | Ok res ->
                     if cmd__095_.flag = Seq
                     then SUT.push sut__096_ res
                     else ()
                 | Error _ -> ());
                res__103_)))
      | Append ->
          Res
            (sut,
              (let a_4__104_ = SUT.get sut__096_ 0 in
               let b__105_ = SUT.get sut__096_ 1 in
               let res__106_ = append a_4__104_ b__105_ in
               (if cmd__095_.flag = Seq
                then SUT.push sut__096_ res__106_
                else ();
                res__106_)))
      | Sub (i_3, n) ->
          Res
            ((result sut exn),
              (let t_6__107_ = SUT.get sut__096_ 0 in
               let res__108_ = protect (fun () -> sub t_6__107_ i_3 n) () in
               ((match res__108_ with
                 | Ok res ->
                     if cmd__095_.flag = Seq
                     then SUT.push sut__096_ res
                     else ()
                 | Error _ -> ());
                res__108_)))
      | Copy ->
          Res
            (sut,
              (let t_7__109_ = SUT.get sut__096_ 0 in
               let res__110_ = copy t_7__109_ in
               (if cmd__095_.flag = Seq
                then SUT.push sut__096_ res__110_
                else ();
                res__110_)))
      | Fill (pos, len, x) ->
          Res
            ((result unit exn),
              (let t_8__111_ = SUT.get sut__096_ 0 in
               let res__112_ =
                 protect (fun () -> fill t_8__111_ pos len x) () in
               res__112_))
      | To_list ->
          Res
            ((list char),
              (let t_9__113_ = SUT.get sut__096_ 0 in
               let res__114_ = to_list t_9__113_ in res__114_))
      | Of_list l ->
          Res
            (sut,
              (let res__115_ = of_list l in
               (if cmd__095_.flag = Seq
                then SUT.push sut__096_ res__115_
                else ();
                res__115_)))
      | Mem a_3 ->
          Res
            (bool,
              (let t_11__116_ = SUT.get sut__096_ 0 in
               let res__117_ = mem a_3 t_11__116_ in res__117_))
      | For_all p ->
          Res
            (bool,
              (let t_12__118_ = SUT.get sut__096_ 0 in
               let res__119_ = for_all (QCheck.Fn.apply p) t_12__118_ in
               res__119_))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_show_cmd cmd__121_ models__122_ last__124_ res__123_ =
  let open Spec in
    let open STM in
      match ((cmd__121_.raw_cmd), res__123_) with
      | (Length, Res ((Int, _), _)) ->
          let lhs = if last__124_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "length"
            (Model.get_name models__122_ (0 + shift))
      | (Get i, Res ((Result (Char, Exn), _), _)) ->
          let lhs = if last__124_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = protect (fun () -> %s %s %a)" lhs "get"
            (Model.get_name models__122_ (0 + shift)) (Util.Pp.pp_int true) i
      | (Set (i_1, a_1), Res ((Result (Unit, Exn), _), _)) ->
          let lhs = if last__124_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = protect (fun () -> %s %s %a %a)" lhs
            "set" (Model.get_name models__122_ (0 + shift))
            (Util.Pp.pp_int true) i_1 (Util.Pp.pp_char true) a_1
      | (Make (i_2, a_2), Res ((Result (SUT, Exn), _), t_4)) ->
          let lhs =
            if last__124_
            then "r"
            else
              (match t_4 with
               | Ok _ -> "Ok " ^ (Model.get_name models__122_ 0)
               | Error _ -> "_")
          and shift = match t_4 with | Ok _ -> 1 | Error _ -> 0 in
          Format.asprintf "let %s = protect (fun () -> %s %a %a)" lhs "make"
            (Util.Pp.pp_int true) i_2 (Util.Pp.pp_char true) a_2
      | (Append, Res ((SUT, _), t_5)) ->
          let lhs = if last__124_ then "r" else Model.get_name models__122_ 0
          and shift = 1 in
          Format.asprintf "let %s = %s %s %s" lhs "append"
            (Model.get_name models__122_ (0 + shift))
            (Model.get_name models__122_ (1 + shift))
      | (Sub (i_3, n), Res ((Result (SUT, Exn), _), r)) ->
          let lhs =
            if last__124_
            then "r"
            else
              (match r with
               | Ok _ -> "Ok " ^ (Model.get_name models__122_ 0)
               | Error _ -> "_")
          and shift = match r with | Ok _ -> 1 | Error _ -> 0 in
          Format.asprintf "let %s = protect (fun () -> %s %s %a %a)" lhs
            "sub" (Model.get_name models__122_ (0 + shift))
            (Util.Pp.pp_int true) i_3 (Util.Pp.pp_int true) n
      | (Copy, Res ((SUT, _), r_1)) ->
          let lhs = if last__124_ then "r" else Model.get_name models__122_ 0
          and shift = 1 in
          Format.asprintf "let %s = %s %s" lhs "copy"
            (Model.get_name models__122_ (0 + shift))
      | (Fill (pos, len, x), Res ((Result (Unit, Exn), _), _)) ->
          let lhs = if last__124_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = protect (fun () -> %s %s %a %a %a)" lhs
            "fill" (Model.get_name models__122_ (0 + shift))
            (Util.Pp.pp_int true) pos (Util.Pp.pp_int true) len
            (Util.Pp.pp_char true) x
      | (To_list, Res ((List (Char), _), _)) ->
          let lhs = if last__124_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "to_list"
            (Model.get_name models__122_ (0 + shift))
      | (Of_list l, Res ((SUT, _), t_10)) ->
          let lhs = if last__124_ then "r" else Model.get_name models__122_ 0
          and shift = 1 in
          Format.asprintf "let %s = %s %a" lhs "of_list"
            (Util.Pp.pp_list Util.Pp.pp_char true) l
      | (Mem a_3, Res ((Bool, _), _)) ->
          let lhs = if last__124_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %a %s" lhs "mem"
            (Util.Pp.pp_char true) a_3
            (Model.get_name models__122_ (0 + shift))
      | (For_all p, Res ((Bool, _), _)) ->
          let lhs = if last__124_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %a %s" lhs "for_all"
            (Util.Pp.pp_fun_ true) p
            (Model.get_name models__122_ (0 + shift))
      | _ -> assert false
let ortac_postcond cmd__050_ state__051_ res__052_ =
  let open Spec in
    let open STM in
      let new_state__053_ = lazy (next_state cmd__050_ state__051_) in
      match ((cmd__050_.raw_cmd), res__052_) with
      | (Length, Res ((Int, _), i_5)) ->
          if
            let t_old__056_ = Model.get state__051_ 0
            and t_new__057_ = lazy (Model.get (Lazy.force new_state__053_) 0) in
            (try
               (Ortac_runtime.Gospelstdlib.integer_of_int i_5) =
                 (Lazy.force t_new__057_).size
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Array" "make 16 'a'"
                 (try
                    Ortac_runtime.Report.Value
                      (Res
                         (integer,
                           (let t_old__054_ = Model.get state__051_ 0
                            and t_new__055_ =
                              lazy (Model.get (Lazy.force new_state__053_) 0) in
                            (Lazy.force t_new__055_).size)))
                  with | e -> Ortac_runtime.Report.Out_of_domain) "length"
                 [("i = t.size",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 7;
                          pos_bol = 250;
                          pos_cnum = 262
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 7;
                          pos_bol = 250;
                          pos_cnum = 272
                        }
                    })])
      | (Get i, Res ((Result (Char, Exn), _), a_5)) ->
          (match if
                   let tmp__063_ = Model.get state__051_ 0 in
                   try
                     let __t1__064_ =
                       Ortac_runtime.Gospelstdlib.(<=)
                         (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i) in
                     let __t2__065_ =
                       Ortac_runtime.Gospelstdlib.(<)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i)
                         tmp__063_.size in
                     __t1__064_ && __t2__065_
                   with | e -> false
                 then None
                 else
                   Some
                     (Ortac_runtime.Report.report "Array" "make 16 'a'"
                        (try
                           Ortac_runtime.Report.Exception "Invalid_argument"
                         with | e -> Ortac_runtime.Report.Out_of_domain)
                        "get"
                        [("0 <= i < t.size",
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 11;
                                 pos_bol = 390;
                                 pos_cnum = 401
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 11;
                                 pos_bol = 390;
                                 pos_cnum = 416
                               }
                           })])
           with
           | None ->
               (match a_5 with
                | Ok a_5 ->
                    if
                      let t_old__061_ = Model.get state__051_ 0
                      and t_new__062_ =
                        lazy (Model.get (Lazy.force new_state__053_) 0) in
                      (try
                         a_5 =
                           (Ortac_runtime.Gospelstdlib.__mix_Bub
                              (Lazy.force t_new__062_).contents
                              (Ortac_runtime.Gospelstdlib.integer_of_int i))
                       with | e -> false)
                    then None
                    else
                      Some
                        (Ortac_runtime.Report.report "Array" "make 16 'a'"
                           (try
                              Ortac_runtime.Report.Protected_value
                                (Res
                                   (char,
                                     (let t_old__059_ =
                                        Model.get state__051_ 0
                                      and t_new__060_ =
                                        lazy
                                          (Model.get
                                             (Lazy.force new_state__053_) 0) in
                                      Ortac_runtime.Gospelstdlib.__mix_Bub
                                        (Lazy.force t_new__060_).contents
                                        (Ortac_runtime.Gospelstdlib.integer_of_int
                                           i))))
                            with | e -> Ortac_runtime.Report.Out_of_domain)
                           "get"
                           [("a = t.contents[i]",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 12;
                                    pos_bol = 417;
                                    pos_cnum = 429
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 12;
                                    pos_bol = 417;
                                    pos_cnum = 446
                                  }
                              })])
                | _ -> None)
           | _ ->
               (match a_5 with
                | Error (Invalid_argument _) -> None
                | _ ->
                    if
                      let tmp__063_ = Model.get state__051_ 0 in
                      (try
                         let __t1__064_ =
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i) in
                         let __t2__065_ =
                           Ortac_runtime.Gospelstdlib.(<)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i)
                             tmp__063_.size in
                         __t1__064_ && __t2__065_
                       with | e -> false)
                    then None
                    else
                      Some
                        (Ortac_runtime.Report.report "Array" "make 16 'a'"
                           (try
                              Ortac_runtime.Report.Exception
                                "Invalid_argument"
                            with | e -> Ortac_runtime.Report.Out_of_domain)
                           "get"
                           [("0 <= i < t.size",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 11;
                                    pos_bol = 390;
                                    pos_cnum = 401
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 11;
                                    pos_bol = 390;
                                    pos_cnum = 416
                                  }
                              })])))
      | (Set (i_1, a_1), Res ((Result (Unit, Exn), _), res)) ->
          (match if
                   let tmp__066_ = Model.get state__051_ 0 in
                   try
                     let __t1__067_ =
                       Ortac_runtime.Gospelstdlib.(<=)
                         (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_1) in
                     let __t2__068_ =
                       Ortac_runtime.Gospelstdlib.(<)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                         tmp__066_.size in
                     __t1__067_ && __t2__068_
                   with | e -> false
                 then None
                 else
                   Some
                     (Ortac_runtime.Report.report "Array" "make 16 'a'"
                        (try
                           Ortac_runtime.Report.Exception "Invalid_argument"
                         with | e -> Ortac_runtime.Report.Out_of_domain)
                        "set"
                        [("0 <= i < t.size",
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 16;
                                 pos_bol = 578;
                                 pos_cnum = 589
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 16;
                                 pos_bol = 578;
                                 pos_cnum = 604
                               }
                           })])
           with
           | None -> (match res with | Ok _ -> None | _ -> None)
           | _ ->
               (match res with
                | Error (Invalid_argument _) -> None
                | _ ->
                    if
                      let tmp__066_ = Model.get state__051_ 0 in
                      (try
                         let __t1__067_ =
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i_1) in
                         let __t2__068_ =
                           Ortac_runtime.Gospelstdlib.(<)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                             tmp__066_.size in
                         __t1__067_ && __t2__068_
                       with | e -> false)
                    then None
                    else
                      Some
                        (Ortac_runtime.Report.report "Array" "make 16 'a'"
                           (try
                              Ortac_runtime.Report.Exception
                                "Invalid_argument"
                            with | e -> Ortac_runtime.Report.Out_of_domain)
                           "set"
                           [("0 <= i < t.size",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 16;
                                    pos_bol = 578;
                                    pos_cnum = 589
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 16;
                                    pos_bol = 578;
                                    pos_cnum = 604
                                  }
                              })])))
      | (Make (i_2, a_2), Res ((Result (SUT, Exn), _), t_4)) ->
          (match if
                   try
                     Ortac_runtime.Gospelstdlib.(>=)
                       (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                       (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   with | e -> false
                 then None
                 else
                   Some
                     (Ortac_runtime.Report.report "Array" "make 16 'a'"
                        (try
                           Ortac_runtime.Report.Exception "Invalid_argument"
                         with | e -> Ortac_runtime.Report.Out_of_domain)
                        "make"
                        [("i >= 0",
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 22;
                                 pos_bol = 844;
                                 pos_cnum = 855
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 22;
                                 pos_bol = 844;
                                 pos_cnum = 861
                               }
                           })])
           with
           | None -> (match t_4 with | Ok t_4 -> None | _ -> None)
           | _ ->
               (match t_4 with
                | Error (Invalid_argument _) -> None
                | _ ->
                    if
                      (try
                         Ortac_runtime.Gospelstdlib.(>=)
                           (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                           (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                       with | e -> false)
                    then None
                    else
                      Some
                        (Ortac_runtime.Report.report "Array" "make 16 'a'"
                           (try
                              Ortac_runtime.Report.Exception
                                "Invalid_argument"
                            with | e -> Ortac_runtime.Report.Out_of_domain)
                           "make"
                           [("i >= 0",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 22;
                                    pos_bol = 844;
                                    pos_cnum = 855
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 22;
                                    pos_bol = 844;
                                    pos_cnum = 861
                                  }
                              })])))
      | (Append, Res ((SUT, _), t_5)) -> None
      | (Sub (i_3, n), Res ((Result (SUT, Exn), _), r)) ->
          (match Ortac_runtime.Report.append
                   (if
                      let tmp__071_ = Model.get state__051_ 0 in
                      try
                        let __t1__072_ =
                          Ortac_runtime.Gospelstdlib.(<=)
                            (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                            (Ortac_runtime.Gospelstdlib.integer_of_int i_3) in
                        let __t2__073_ =
                          Ortac_runtime.Gospelstdlib.(<=)
                            (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                            (Ortac_runtime.Gospelstdlib.Sequence.length
                               tmp__071_.contents) in
                        __t1__072_ && __t2__073_
                      with | e -> false
                    then None
                    else
                      Some
                        (Ortac_runtime.Report.report "Array" "make 16 'a'"
                           (try
                              Ortac_runtime.Report.Exception
                                "Invalid_argument"
                            with | e -> Ortac_runtime.Report.Out_of_domain)
                           "sub"
                           [("0 <= i <= Sequence.length t.contents",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 33;
                                    pos_bol = 1340;
                                    pos_cnum = 1351
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 33;
                                    pos_bol = 1340;
                                    pos_cnum = 1387
                                  }
                              })]))
                   (if
                      let tmp__071_ = Model.get state__051_ 0 in
                      try
                        let __t1__074_ =
                          Ortac_runtime.Gospelstdlib.(<=)
                            (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                            (Ortac_runtime.Gospelstdlib.(+)
                               (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                               (Ortac_runtime.Gospelstdlib.integer_of_int n)) in
                        let __t2__075_ =
                          Ortac_runtime.Gospelstdlib.(<=)
                            (Ortac_runtime.Gospelstdlib.(+)
                               (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                               (Ortac_runtime.Gospelstdlib.integer_of_int n))
                            (Ortac_runtime.Gospelstdlib.Sequence.length
                               tmp__071_.contents) in
                        __t1__074_ && __t2__075_
                      with | e -> false
                    then None
                    else
                      Some
                        (Ortac_runtime.Report.report "Array" "make 16 'a'"
                           (try
                              Ortac_runtime.Report.Exception
                                "Invalid_argument"
                            with | e -> Ortac_runtime.Report.Out_of_domain)
                           "sub"
                           [("i <= i + n <= Sequence.length t.contents",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 34;
                                    pos_bol = 1388;
                                    pos_cnum = 1399
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 34;
                                    pos_bol = 1388;
                                    pos_cnum = 1439
                                  }
                              })]))
           with
           | None -> (match r with | Ok r -> None | _ -> None)
           | _ ->
               (match r with
                | Error (Invalid_argument _) -> None
                | _ ->
                    Ortac_runtime.Report.append
                      (if
                         let tmp__071_ = Model.get state__051_ 0 in
                         try
                           let __t1__072_ =
                             Ortac_runtime.Gospelstdlib.(<=)
                               (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                               (Ortac_runtime.Gospelstdlib.integer_of_int i_3) in
                           let __t2__073_ =
                             Ortac_runtime.Gospelstdlib.(<=)
                               (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                               (Ortac_runtime.Gospelstdlib.Sequence.length
                                  tmp__071_.contents) in
                           __t1__072_ && __t2__073_
                         with | e -> false
                       then None
                       else
                         Some
                           (Ortac_runtime.Report.report "Array" "make 16 'a'"
                              (try
                                 Ortac_runtime.Report.Exception
                                   "Invalid_argument"
                               with | e -> Ortac_runtime.Report.Out_of_domain)
                              "sub"
                              [("0 <= i <= Sequence.length t.contents",
                                 {
                                   Ortac_runtime.start =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 33;
                                       pos_bol = 1340;
                                       pos_cnum = 1351
                                     };
                                   Ortac_runtime.stop =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 33;
                                       pos_bol = 1340;
                                       pos_cnum = 1387
                                     }
                                 })]))
                      (if
                         let tmp__071_ = Model.get state__051_ 0 in
                         try
                           let __t1__074_ =
                             Ortac_runtime.Gospelstdlib.(<=)
                               (Ortac_runtime.Gospelstdlib.integer_of_int i_3)
                               (Ortac_runtime.Gospelstdlib.(+)
                                  (Ortac_runtime.Gospelstdlib.integer_of_int
                                     i_3)
                                  (Ortac_runtime.Gospelstdlib.integer_of_int
                                     n)) in
                           let __t2__075_ =
                             Ortac_runtime.Gospelstdlib.(<=)
                               (Ortac_runtime.Gospelstdlib.(+)
                                  (Ortac_runtime.Gospelstdlib.integer_of_int
                                     i_3)
                                  (Ortac_runtime.Gospelstdlib.integer_of_int
                                     n))
                               (Ortac_runtime.Gospelstdlib.Sequence.length
                                  tmp__071_.contents) in
                           __t1__074_ && __t2__075_
                         with | e -> false
                       then None
                       else
                         Some
                           (Ortac_runtime.Report.report "Array" "make 16 'a'"
                              (try
                                 Ortac_runtime.Report.Exception
                                   "Invalid_argument"
                               with | e -> Ortac_runtime.Report.Out_of_domain)
                              "sub"
                              [("i <= i + n <= Sequence.length t.contents",
                                 {
                                   Ortac_runtime.start =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 34;
                                       pos_bol = 1388;
                                       pos_cnum = 1399
                                     };
                                   Ortac_runtime.stop =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 34;
                                       pos_bol = 1388;
                                       pos_cnum = 1439
                                     }
                                 })]))))
      | (Copy, Res ((SUT, _), r_1)) -> None
      | (Fill (pos, len, x), Res ((Result (Unit, Exn), _), res)) ->
          (match Ortac_runtime.Report.append
                   (if
                      let tmp__077_ = Model.get state__051_ 0 in
                      try
                        Ortac_runtime.Gospelstdlib.(<=)
                          (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                          (Ortac_runtime.Gospelstdlib.integer_of_int pos)
                      with | e -> false
                    then None
                    else
                      Some
                        (Ortac_runtime.Report.report "Array" "make 16 'a'"
                           (try
                              Ortac_runtime.Report.Exception
                                "Invalid_argument"
                            with | e -> Ortac_runtime.Report.Out_of_domain)
                           "fill"
                           [("0 <= pos",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 45;
                                    pos_bol = 1929;
                                    pos_cnum = 1940
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 45;
                                    pos_bol = 1929;
                                    pos_cnum = 1948
                                  }
                              })]))
                   (Ortac_runtime.Report.append
                      (if
                         let tmp__077_ = Model.get state__051_ 0 in
                         try
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                             (Ortac_runtime.Gospelstdlib.integer_of_int len)
                         with | e -> false
                       then None
                       else
                         Some
                           (Ortac_runtime.Report.report "Array" "make 16 'a'"
                              (try
                                 Ortac_runtime.Report.Exception
                                   "Invalid_argument"
                               with | e -> Ortac_runtime.Report.Out_of_domain)
                              "fill"
                              [("0 <= len",
                                 {
                                   Ortac_runtime.start =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 46;
                                       pos_bol = 1949;
                                       pos_cnum = 1960
                                     };
                                   Ortac_runtime.stop =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 46;
                                       pos_bol = 1949;
                                       pos_cnum = 1968
                                     }
                                 })]))
                      (if
                         let tmp__077_ = Model.get state__051_ 0 in
                         try
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.(+)
                                (Ortac_runtime.Gospelstdlib.integer_of_int
                                   pos)
                                (Ortac_runtime.Gospelstdlib.integer_of_int
                                   len)) tmp__077_.size
                         with | e -> false
                       then None
                       else
                         Some
                           (Ortac_runtime.Report.report "Array" "make 16 'a'"
                              (try
                                 Ortac_runtime.Report.Exception
                                   "Invalid_argument"
                               with | e -> Ortac_runtime.Report.Out_of_domain)
                              "fill"
                              [("pos + len <= t.size",
                                 {
                                   Ortac_runtime.start =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 47;
                                       pos_bol = 1969;
                                       pos_cnum = 1980
                                     };
                                   Ortac_runtime.stop =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 47;
                                       pos_bol = 1969;
                                       pos_cnum = 1999
                                     }
                                 })])))
           with
           | None -> (match res with | Ok _ -> None | _ -> None)
           | _ ->
               (match res with
                | Error (Invalid_argument _) -> None
                | _ ->
                    Ortac_runtime.Report.append
                      (if
                         let tmp__077_ = Model.get state__051_ 0 in
                         try
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                             (Ortac_runtime.Gospelstdlib.integer_of_int pos)
                         with | e -> false
                       then None
                       else
                         Some
                           (Ortac_runtime.Report.report "Array" "make 16 'a'"
                              (try
                                 Ortac_runtime.Report.Exception
                                   "Invalid_argument"
                               with | e -> Ortac_runtime.Report.Out_of_domain)
                              "fill"
                              [("0 <= pos",
                                 {
                                   Ortac_runtime.start =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 45;
                                       pos_bol = 1929;
                                       pos_cnum = 1940
                                     };
                                   Ortac_runtime.stop =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 45;
                                       pos_bol = 1929;
                                       pos_cnum = 1948
                                     }
                                 })]))
                      (Ortac_runtime.Report.append
                         (if
                            let tmp__077_ = Model.get state__051_ 0 in
                            try
                              Ortac_runtime.Gospelstdlib.(<=)
                                (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                                (Ortac_runtime.Gospelstdlib.integer_of_int
                                   len)
                            with | e -> false
                          then None
                          else
                            Some
                              (Ortac_runtime.Report.report "Array"
                                 "make 16 'a'"
                                 (try
                                    Ortac_runtime.Report.Exception
                                      "Invalid_argument"
                                  with
                                  | e -> Ortac_runtime.Report.Out_of_domain)
                                 "fill"
                                 [("0 <= len",
                                    {
                                      Ortac_runtime.start =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 46;
                                          pos_bol = 1949;
                                          pos_cnum = 1960
                                        };
                                      Ortac_runtime.stop =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 46;
                                          pos_bol = 1949;
                                          pos_cnum = 1968
                                        }
                                    })]))
                         (if
                            let tmp__077_ = Model.get state__051_ 0 in
                            try
                              Ortac_runtime.Gospelstdlib.(<=)
                                (Ortac_runtime.Gospelstdlib.(+)
                                   (Ortac_runtime.Gospelstdlib.integer_of_int
                                      pos)
                                   (Ortac_runtime.Gospelstdlib.integer_of_int
                                      len)) tmp__077_.size
                            with | e -> false
                          then None
                          else
                            Some
                              (Ortac_runtime.Report.report "Array"
                                 "make 16 'a'"
                                 (try
                                    Ortac_runtime.Report.Exception
                                      "Invalid_argument"
                                  with
                                  | e -> Ortac_runtime.Report.Out_of_domain)
                                 "fill"
                                 [("pos + len <= t.size",
                                    {
                                      Ortac_runtime.start =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 47;
                                          pos_bol = 1969;
                                          pos_cnum = 1980
                                        };
                                      Ortac_runtime.stop =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 47;
                                          pos_bol = 1969;
                                          pos_cnum = 1999
                                        }
                                    })])))))
      | (To_list, Res ((List (Char), _), l_1)) ->
          if
            let t_old__080_ = Model.get state__051_ 0
            and t_new__081_ = lazy (Model.get (Lazy.force new_state__053_) 0) in
            (try
               l_1 =
                 (Ortac_runtime.Gospelstdlib.List.of_seq
                    (Lazy.force t_new__081_).contents)
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Array" "make 16 'a'"
                 (try
                    Ortac_runtime.Report.Value
                      (Res
                         ((list char),
                           (let t_old__078_ = Model.get state__051_ 0
                            and t_new__079_ =
                              lazy (Model.get (Lazy.force new_state__053_) 0) in
                            Ortac_runtime.Gospelstdlib.List.of_seq
                              (Lazy.force t_new__079_).contents)))
                  with | e -> Ortac_runtime.Report.Out_of_domain) "to_list"
                 [("l = List.of_seq t.contents",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 53;
                          pos_bol = 2405;
                          pos_cnum = 2417
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 53;
                          pos_bol = 2405;
                          pos_cnum = 2443
                        }
                    })])
      | (Of_list l, Res ((SUT, _), t_10)) -> None
      | (Mem a_3, Res ((Bool, _), b_1)) ->
          if
            let t_old__085_ = Model.get state__051_ 0
            and t_new__086_ = lazy (Model.get (Lazy.force new_state__053_) 0) in
            (try
               (b_1 = true) =
                 (Ortac_runtime.Gospelstdlib.Sequence.mem
                    (Lazy.force t_new__086_).contents a_3)
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Array" "make 16 'a'"
                 (try
                    Ortac_runtime.Report.Value
                      (Res
                         (bool,
                           (let t_old__083_ = Model.get state__051_ 0
                            and t_new__084_ =
                              lazy (Model.get (Lazy.force new_state__053_) 0) in
                            Ortac_runtime.Gospelstdlib.Sequence.mem
                              (Lazy.force t_new__084_).contents a_3)))
                  with | e -> Ortac_runtime.Report.Out_of_domain) "mem"
                 [("b = Sequence.mem t.contents a",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 62;
                          pos_bol = 2791;
                          pos_cnum = 2803
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 62;
                          pos_bol = 2791;
                          pos_cnum = 2832
                        }
                    })])
      | (For_all p, Res ((Bool, _), b_2)) ->
          if
            let t_old__090_ = Model.get state__051_ 0
            and t_new__091_ = lazy (Model.get (Lazy.force new_state__053_) 0) in
            (try
               b_2 =
                 (Ortac_runtime.Gospelstdlib.Sequence.fold_left
                    (fun acc a_6 ->
                       if ((QCheck.Fn.apply p a_6) = true) && (acc = true)
                       then true
                       else false) true (Lazy.force t_new__091_).contents)
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Array" "make 16 'a'"
                 (try
                    Ortac_runtime.Report.Value
                      (Res
                         (bool,
                           (let t_old__088_ = Model.get state__051_ 0
                            and t_new__089_ =
                              lazy (Model.get (Lazy.force new_state__053_) 0) in
                            Ortac_runtime.Gospelstdlib.Sequence.fold_left
                              (fun acc a_6 ->
                                 if
                                   ((QCheck.Fn.apply p a_6) = true) &&
                                     (acc = true)
                                 then true
                                 else false) true
                              (Lazy.force t_new__089_).contents)))
                  with | e -> Ortac_runtime.Report.Out_of_domain) "for_all"
                 [("b = Sequence.fold_left (fun acc a -> p a && acc) true t.contents",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 66;
                          pos_bol = 2989;
                          pos_cnum = 3001
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 66;
                          pos_bol = 2989;
                          pos_cnum = 3065
                        }
                    })])
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Array STM tests" 2 check_init_state
        ortac_show_cmd ortac_postcond])
