(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32-38"]
open Conjunctive_clauses
module Ortac_runtime = Ortac_runtime_qcheck_stm
let set_contents c i a_1 =
  try
    Ortac_runtime.Gospelstdlib.List.mapi
      (fun j -> fun x -> if i = j then a_1 else x) c
  with
  | e ->
      raise
        (Ortac_runtime.Partial_function
           (e,
             {
               Ortac_runtime.start =
                 {
                   pos_fname = "conjunctive_clauses.mli";
                   pos_lnum = 10;
                   pos_bol = 580;
                   pos_cnum = 590
                 };
               Ortac_runtime.stop =
                 {
                   pos_fname = "conjunctive_clauses.mli";
                   pos_lnum = 10;
                   pos_bol = 580;
                   pos_cnum = 637
                 }
             }))
module SUT =
  (Ortac_runtime.SUT.Make)(struct
                             type sut = char t
                             let init () = make 42 'a'
                           end)
module ModelElt =
  struct
    type nonrec elt = {
      contents: char list }
    let init =
      let i_1 = 42
      and a_2 = 'a' in
      {
        contents =
          (try
             Ortac_runtime.Gospelstdlib.List.init
               (Ortac_runtime.Gospelstdlib.integer_of_int i_1) (fun _ -> a_2)
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "conjunctive_clauses.mli";
                            pos_lnum = 7;
                            pos_bol = 295;
                            pos_cnum = 336
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "conjunctive_clauses.mli";
                            pos_lnum = 7;
                            pos_bol = 295;
                            pos_cnum = 360
                          }
                      })))
      }
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type _ ty +=  
      | SUT: SUT.elt ty 
    let sut = (SUT, (fun _ -> "<sut>"))
    type sut = SUT.t
    let init_sut = SUT.create 1
    type state = Model.t
    let init_state = Model.create 1 ()
    type cmd =
      | Make of int * char 
      | Set of int * char 
    let show_cmd cmd__001_ =
      match cmd__001_ with
      | Make (i_1, a_2) ->
          Format.asprintf "protect (fun () -> %s %a %a)" "make"
            (Util.Pp.pp_int true) i_1 (Util.Pp.pp_char true) a_2
      | Set (i_2, a_3) ->
          Format.asprintf "protect (fun () -> %s <sut> %a %a)" "set"
            (Util.Pp.pp_int true) i_2 (Util.Pp.pp_char true) a_3
    let shrink_cmd cmd__002_ =
      let open QCheck in
        let open Shrink in
          let open Iter in
            match cmd__002_ with
            | Make (i_1, a_2) ->
                (map (fun i_1 -> Make (i_1, a_2)) (int i_1)) <+>
                  (map (fun a_2 -> Make (i_1, a_2)) (char a_2))
            | Set (i_2, a_3) ->
                (map (fun i_2 -> Set (i_2, a_3)) (int i_2)) <+>
                  (map (fun a_3 -> Set (i_2, a_3)) (char a_3))
    let cleanup _ = ()
    let arb_cmd _ =
      let open QCheck in
        make ~print:show_cmd ~shrink:shrink_cmd
          (let open Gen in
             oneof
               [((pure (fun i_1 -> fun a_2 -> Make (i_1, a_2))) <*>
                   small_signed_int)
                  <*> char;
               ((pure (fun i_2 -> fun a_3 -> Set (i_2, a_3))) <*> int) <*>
                 char])
    let next_state cmd__003_ state__004_ =
      match cmd__003_ with
      | Make (i_1, a_2) ->
          if
            (try
               Ortac_runtime.Gospelstdlib.(>=)
                 (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                 (Ortac_runtime.Gospelstdlib.integer_of_int 0)
             with
             | e ->
                 raise
                   (Ortac_runtime.Partial_function
                      (e,
                        {
                          Ortac_runtime.start =
                            {
                              pos_fname = "conjunctive_clauses.mli";
                              pos_lnum = 6;
                              pos_bol = 277;
                              pos_cnum = 288
                            };
                          Ortac_runtime.stop =
                            {
                              pos_fname = "conjunctive_clauses.mli";
                              pos_lnum = 6;
                              pos_bol = 277;
                              pos_cnum = 294
                            }
                        })))
          then
            let t_1__006_ =
              let open ModelElt in
                {
                  contents =
                    (try
                       Ortac_runtime.Gospelstdlib.List.init
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                         (fun _ -> a_2)
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "conjunctive_clauses.mli";
                                      pos_lnum = 7;
                                      pos_bol = 295;
                                      pos_cnum = 336
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "conjunctive_clauses.mli";
                                      pos_lnum = 7;
                                      pos_bol = 295;
                                      pos_cnum = 360
                                    }
                                })))
                } in
            Model.push (Model.drop_n state__004_ 0) t_1__006_
          else state__004_
      | Set (i_2, a_3) ->
          let t_2__007_ = Model.get state__004_ 0 in
          if
            (try
               let __t1__009_ =
                 Ortac_runtime.Gospelstdlib.(<=)
                   (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i_2) in
               let __t2__010_ =
                 Ortac_runtime.Gospelstdlib.(<)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                   (Ortac_runtime.Gospelstdlib.List.length t_2__007_.contents) in
               __t1__009_ && __t2__010_
             with
             | e ->
                 raise
                   (Ortac_runtime.Partial_function
                      (e,
                        {
                          Ortac_runtime.start =
                            {
                              pos_fname = "conjunctive_clauses.mli";
                              pos_lnum = 14;
                              pos_bol = 825;
                              pos_cnum = 836
                            };
                          Ortac_runtime.stop =
                            {
                              pos_fname = "conjunctive_clauses.mli";
                              pos_lnum = 14;
                              pos_bol = 825;
                              pos_cnum = 867
                            }
                        })))
          then
            let t_2__008_ =
              let open ModelElt in
                {
                  contents =
                    (try
                       set_contents t_2__007_.contents
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_2) a_3
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "conjunctive_clauses.mli";
                                      pos_lnum = 16;
                                      pos_bol = 883;
                                      pos_cnum = 924
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "conjunctive_clauses.mli";
                                      pos_lnum = 16;
                                      pos_bol = 883;
                                      pos_cnum = 936
                                    }
                                })))
                } in
            Model.push (Model.drop_n state__004_ 1) t_2__008_
          else state__004_
    let precond cmd__018_ state__019_ =
      match cmd__018_ with | Make (i_1, a_2) -> true | Set (i_2, a_3) -> true
    let postcond _ _ _ = true
    let run cmd__020_ sut__021_ =
      match cmd__020_ with
      | Make (i_1, a_2) ->
          Res
            ((result sut exn),
              (let res__022_ = protect (fun () -> make i_1 a_2) () in
               ((match res__022_ with
                 | Ok res -> SUT.push sut__021_ res
                 | Error _ -> ());
                res__022_)))
      | Set (i_2, a_3) ->
          Res
            ((result unit exn),
              (let t_2__023_ = SUT.pop sut__021_ in
               let res__024_ = protect (fun () -> set t_2__023_ i_2 a_3) () in
               (SUT.push sut__021_ t_2__023_; res__024_)))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_show_cmd cmd__026_ state__027_ last__029_ res__028_ =
  let open Spec in
    let open STM in
      match (cmd__026_, res__028_) with
      | (Make (i_1, a_2), Res ((Result (SUT, Exn), _), t_1)) ->
          let lhs =
            if last__029_
            then "r"
            else
              (match t_1 with
               | Ok _ -> "Ok " ^ (SUT.get_name state__027_ 0)
               | Error _ -> "_")
          and shift = match t_1 with | Ok _ -> 1 | Error _ -> 0 in
          Format.asprintf "let %s = protect (fun () -> %s %a %a)" lhs "make"
            (Util.Pp.pp_int true) i_1 (Util.Pp.pp_char true) a_2
      | (Set (i_2, a_3), Res ((Result (Unit, Exn), _), _)) ->
          let lhs = if last__029_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = protect (fun () -> %s %s %a %a)" lhs
            "set" (SUT.get_name state__027_ (0 + shift))
            (Util.Pp.pp_int true) i_2 (Util.Pp.pp_char true) a_3
      | _ -> assert false
let ortac_postcond cmd__011_ state__012_ res__013_ =
  let open Spec in
    let open STM in
      let new_state__014_ = lazy (next_state cmd__011_ state__012_) in
      match (cmd__011_, res__013_) with
      | (Make (i_1, a_2), Res ((Result (SUT, Exn), _), t_1)) ->
          (match if
                   try
                     Ortac_runtime.Gospelstdlib.(>=)
                       (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                       (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 6;
                                    pos_bol = 277;
                                    pos_cnum = 288
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 6;
                                    pos_bol = 277;
                                    pos_cnum = 294
                                  }
                              }))
                 then None
                 else
                   Some
                     (Ortac_runtime.report "Conjunctive_clauses"
                        "make 42 'a'"
                        (Ortac_runtime.Exception "Invalid_argument") "make"
                        [("i >= 0",
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "conjunctive_clauses.mli";
                                 pos_lnum = 6;
                                 pos_bol = 277;
                                 pos_cnum = 288
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "conjunctive_clauses.mli";
                                 pos_lnum = 6;
                                 pos_bol = 277;
                                 pos_cnum = 294
                               }
                           })])
           with
           | None -> (match t_1 with | Ok t_1 -> None | _ -> None)
           | _ ->
               (match t_1 with
                | Error (Invalid_argument _) -> None
                | _ ->
                    if
                      (try
                         Ortac_runtime.Gospelstdlib.(>=)
                           (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                           (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                       with
                       | e ->
                           raise
                             (Ortac_runtime.Partial_function
                                (e,
                                  {
                                    Ortac_runtime.start =
                                      {
                                        pos_fname = "conjunctive_clauses.mli";
                                        pos_lnum = 6;
                                        pos_bol = 277;
                                        pos_cnum = 288
                                      };
                                    Ortac_runtime.stop =
                                      {
                                        pos_fname = "conjunctive_clauses.mli";
                                        pos_lnum = 6;
                                        pos_bol = 277;
                                        pos_cnum = 294
                                      }
                                  })))
                    then None
                    else
                      Some
                        (Ortac_runtime.report "Conjunctive_clauses"
                           "make 42 'a'"
                           (Ortac_runtime.Exception "Invalid_argument")
                           "make"
                           [("i >= 0",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 6;
                                    pos_bol = 277;
                                    pos_cnum = 288
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 6;
                                    pos_bol = 277;
                                    pos_cnum = 294
                                  }
                              })])))
      | (Set (i_2, a_3), Res ((Result (Unit, Exn), _), res)) ->
          (match if
                   let tmp__015_ = Model.get state__012_ 0 in
                   try
                     let __t1__016_ =
                       Ortac_runtime.Gospelstdlib.(<=)
                         (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_2) in
                     let __t2__017_ =
                       Ortac_runtime.Gospelstdlib.(<)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                         (Ortac_runtime.Gospelstdlib.List.length
                            tmp__015_.contents) in
                     __t1__016_ && __t2__017_
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 14;
                                    pos_bol = 825;
                                    pos_cnum = 836
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 14;
                                    pos_bol = 825;
                                    pos_cnum = 867
                                  }
                              }))
                 then None
                 else
                   Some
                     (Ortac_runtime.report "Conjunctive_clauses"
                        "make 42 'a'"
                        (Ortac_runtime.Exception "Invalid_argument") "set"
                        [("0 <= i < List.length t.contents",
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "conjunctive_clauses.mli";
                                 pos_lnum = 14;
                                 pos_bol = 825;
                                 pos_cnum = 836
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "conjunctive_clauses.mli";
                                 pos_lnum = 14;
                                 pos_bol = 825;
                                 pos_cnum = 867
                               }
                           })])
           with
           | None -> (match res with | Ok _ -> None | _ -> None)
           | _ ->
               (match res with
                | Error (Invalid_argument _) -> None
                | _ ->
                    if
                      let tmp__015_ = Model.get state__012_ 0 in
                      (try
                         let __t1__016_ =
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i_2) in
                         let __t2__017_ =
                           Ortac_runtime.Gospelstdlib.(<)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                             (Ortac_runtime.Gospelstdlib.List.length
                                tmp__015_.contents) in
                         __t1__016_ && __t2__017_
                       with
                       | e ->
                           raise
                             (Ortac_runtime.Partial_function
                                (e,
                                  {
                                    Ortac_runtime.start =
                                      {
                                        pos_fname = "conjunctive_clauses.mli";
                                        pos_lnum = 14;
                                        pos_bol = 825;
                                        pos_cnum = 836
                                      };
                                    Ortac_runtime.stop =
                                      {
                                        pos_fname = "conjunctive_clauses.mli";
                                        pos_lnum = 14;
                                        pos_bol = 825;
                                        pos_cnum = 867
                                      }
                                  })))
                    then None
                    else
                      Some
                        (Ortac_runtime.report "Conjunctive_clauses"
                           "make 42 'a'"
                           (Ortac_runtime.Exception "Invalid_argument") "set"
                           [("0 <= i < List.length t.contents",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 14;
                                    pos_bol = 825;
                                    pos_cnum = 836
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 14;
                                    pos_bol = 825;
                                    pos_cnum = 867
                                  }
                              })])))
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Conjunctive_clauses STM tests" 1
        check_init_state ortac_show_cmd ortac_postcond])
