(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27"]
open Custom_config
module Ortac_runtime = Ortac_runtime_qcheck_stm
module Spec =
  struct
    open STM
    module QCheck =
      struct
        include QCheck
        module Gen =
          struct
            include Gen
            let int = small_signed_int
            let elt gen = elt <$> gen
          end
      end
    module Util =
      struct
        module Pp =
          struct
            include Util.Pp
            let pp_elt pp par fmt e =
              let open Format in fprintf fmt "(Elt %a)" (pp par) (proj e)
          end
      end
    type sut = int t
    type cmd =
      | Push of int elt 
    let show_cmd cmd__001_ =
      match cmd__001_ with
      | Push e ->
          Format.asprintf "%s sut %a" "push"
            (Util.Pp.pp_elt Util.Pp.pp_int true) e
    type nonrec state = {
      contents: int Ortac_runtime.Gospelstdlib.sequence }
    let init_state =
      let () = () in
      {
        contents =
          (try Ortac_runtime.Gospelstdlib.Sequence.empty
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "custom_config.mli";
                            pos_lnum = 12;
                            pos_bol = 401;
                            pos_cnum = 426
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "custom_config.mli";
                            pos_lnum = 12;
                            pos_bol = 401;
                            pos_cnum = 440
                          }
                      })))
      }
    let init_sut () = empty ()
    let cleanup _ = ()
    let arb_cmd _ =
      let open QCheck in
        make ~print:show_cmd
          (let open Gen in oneof [(pure (fun e -> Push e)) <*> (elt int)])
    let next_state cmd__002_ state__003_ =
      match cmd__002_ with
      | Push e ->
          {
            contents =
              ((try
                  Ortac_runtime.Gospelstdlib.Sequence.cons (proj e)
                    state__003_.contents
                with
                | e ->
                    raise
                      (Ortac_runtime.Partial_function
                         (e,
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "custom_config.mli";
                                 pos_lnum = 17;
                                 pos_bol = 619;
                                 pos_cnum = 644
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "custom_config.mli";
                                 pos_lnum = 17;
                                 pos_bol = 619;
                                 pos_cnum = 683
                               }
                           }))))
          }
    let precond cmd__008_ state__009_ = match cmd__008_ with | Push e -> true
    let postcond _ _ _ = true
    let run cmd__010_ sut__011_ =
      match cmd__010_ with | Push e -> Res (unit, (push sut__011_ e))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_postcond cmd__004_ state__005_ res__006_ =
  let open Spec in
    let open STM in
      let new_state__007_ = lazy (next_state cmd__004_ state__005_) in
      match (cmd__004_, res__006_) with
      | (Push e, Res ((Unit, _), _)) -> None
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Custom_config STM tests"
        check_init_state ortac_postcond])
