(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32-34-37-38"]
open Ghost_as_model
module Ortac_runtime = Ortac_runtime_qcheck_stm_sequential
type m =
  | A of Ortac_runtime.integer 
module SUT =
  (Ortac_runtime.SUT.Make)(struct type sut = t
                                  let init () = create () end)
module ModelElt =
  struct
    type nonrec elt = {
      m_1: m }
    let init =
      let () = () in
      {
        m_1 =
          (try A (Ortac_runtime.Gospelstdlib.integer_of_int 0)
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "ghost_as_model.mli";
                            pos_lnum = 8;
                            pos_bol = 343;
                            pos_cnum = 361
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "ghost_as_model.mli";
                            pos_lnum = 8;
                            pos_bol = 343;
                            pos_cnum = 362
                          }
                      })))
      }
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type _ ty +=  
      | SUT: SUT.elt ty 
    let sut = (SUT, (fun _ -> "<sut>"))
    type sut = SUT.t
    let init_sut = SUT.create 1
    type state = Model.t
    let init_state = Model.create 1 ()
    type raw_cmd =
      | Create of unit 
      | Use 
    type flag =
      | Seq 
      | Dom 
    type flagged_cmd = {
      flag: flag ;
      raw_cmd: raw_cmd }
    let with_flag flag raw_cmd = { flag; raw_cmd }
    type cmd =
      | Create of unit 
      | Use 
    let show_cmd cmd__005_ =
      match cmd__005_ with
      | Create () ->
          Format.asprintf "%s %a" "create" (Util.Pp.pp_unit true) ()
      | Use -> Format.asprintf "%s <sut>" "use"
    let cleanup _ = ()
    let gen_cmd _ =
      let open QCheck in
        let open Gen in
          oneof_weighted
            [(1, ((pure (fun () -> Create ())) <*> unit)); (1, (pure Use))]
    let arb_cmd state__001_ =
      let open QCheck in make ~print:show_cmd (gen_cmd state__001_)
    let next_state cmd__006_ state__007_ =
      match cmd__006_ with
      | Create () ->
          let t_1__009_ =
            let open ModelElt in
              {
                m_1 =
                  (try A (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "ghost_as_model.mli";
                                    pos_lnum = 8;
                                    pos_bol = 343;
                                    pos_cnum = 361
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "ghost_as_model.mli";
                                    pos_lnum = 8;
                                    pos_bol = 343;
                                    pos_cnum = 362
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__007_ 0) t_1__009_
      | Use ->
          let t_2__010_ = Model.get state__007_ 0 in
          let t_2__011_ =
            let open ModelElt in
              {
                m_1 =
                  (try
                     match t_2__010_.m_1 with
                     | A x -> A (Ortac_runtime.Gospelstdlib.succ x)
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "ghost_as_model.mli";
                                    pos_lnum = 13;
                                    pos_bol = 502;
                                    pos_cnum = 520
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "ghost_as_model.mli";
                                    pos_lnum = 13;
                                    pos_bol = 502;
                                    pos_cnum = 556
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__007_ 1) t_2__011_
    let precond cmd__017_ state__018_ =
      match cmd__017_ with | Create () -> true | Use -> true
    let postcond _ _ _ = true
    let run cmd__019_ sut__020_ =
      match cmd__019_ with
      | Create () ->
          Res
            (sut,
              (let res__021_ = create () in
               (SUT.push sut__020_ res__021_; res__021_)))
      | Use ->
          Res
            (unit,
              (let t_2__022_ = SUT.get sut__020_ 0 in
               let res__023_ = use t_2__022_ in res__023_))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_show_cmd cmd__025_ models__026_ last__028_ res__027_ =
  let open Spec in
    let open STM in
      match (cmd__025_, res__027_) with
      | (Create (), Res ((SUT, _), t_1)) ->
          let lhs = if last__028_ then "r" else Model.get_name models__026_ 0
          and shift = 1 in
          Format.asprintf "let %s = %s %a" lhs "create"
            (Util.Pp.pp_unit true) ()
      | (Use, Res ((Unit, _), _)) ->
          let lhs = if last__028_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "use"
            (Model.get_name models__026_ (0 + shift))
      | _ -> assert false
let ortac_postcond cmd__012_ state__013_ res__014_ =
  let open Spec in
    let open STM in
      let new_state__015_ = lazy (next_state cmd__012_ state__013_) in
      match (cmd__012_, res__014_) with
      | (Create (), Res ((SUT, _), t_1)) -> None
      | (Use, Res ((Unit, _), _)) -> None
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Ghost_as_model STM tests" 1
        check_init_state ortac_show_cmd ortac_postcond])
