(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32-38"]
open Sequence_model
module Ortac_runtime = Ortac_runtime_qcheck_stm
let length_opt s =
  try Some (Ortac_runtime.Gospelstdlib.Sequence.length s)
  with
  | e ->
      raise
        (Ortac_runtime.Partial_function
           (e,
             {
               Ortac_runtime.start =
                 {
                   pos_fname = "sequence_model.mli";
                   pos_lnum = 15;
                   pos_bol = 750;
                   pos_cnum = 756
                 };
               Ortac_runtime.stop =
                 {
                   pos_fname = "sequence_model.mli";
                   pos_lnum = 15;
                   pos_bol = 750;
                   pos_cnum = 760
                 }
             }))
module SUT =
  (Ortac_runtime.SUT.Make)(struct
                             type sut = char t
                             let init () = create ()
                           end)
module ModelElt =
  struct
    type nonrec elt = {
      contents: char Ortac_runtime.Gospelstdlib.sequence }
    let init =
      let () = () in
      {
        contents =
          (try Ortac_runtime.Gospelstdlib.Sequence.empty
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "sequence_model.mli";
                            pos_lnum = 6;
                            pos_bol = 263;
                            pos_cnum = 288
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "sequence_model.mli";
                            pos_lnum = 6;
                            pos_bol = 263;
                            pos_cnum = 302
                          }
                      })))
      }
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type _ ty +=  
      | SUT: SUT.elt ty 
    let sut = (SUT, (fun _ -> "<sut>"))
    type sut = SUT.t
    let init_sut = SUT.create 1
    type state = Model.t
    let init_state = Model.create 1 ()
    type cmd =
      | Create of unit 
      | Add of char 
      | Remove 
      | Remove_ 
    let show_cmd cmd__001_ =
      match cmd__001_ with
      | Create () ->
          Format.asprintf "%s %a" "create" (Util.Pp.pp_unit true) ()
      | Add v -> Format.asprintf "%s %a <sut>" "add" (Util.Pp.pp_char true) v
      | Remove -> Format.asprintf "%s <sut>" "remove"
      | Remove_ -> Format.asprintf "%s <sut>" "remove_"
    let shrink_cmd cmd__002_ =
      let open QCheck in
        let open Shrink in
          let open Iter in
            match cmd__002_ with
            | Create () -> map (fun () -> Create ()) (unit ())
            | Add v -> map (fun v -> Add v) (char v)
            | Remove -> empty
            | Remove_ -> empty
    let cleanup _ = ()
    let arb_cmd _ =
      let open QCheck in
        make ~print:show_cmd ~shrink:shrink_cmd
          (let open Gen in
             oneof
               [(pure (fun () -> Create ())) <*> unit;
               (pure (fun v -> Add v)) <*> char;
               pure Remove;
               pure Remove_])
    let next_state cmd__003_ state__004_ =
      match cmd__003_ with
      | Create () ->
          let t_1__006_ =
            let open ModelElt in
              {
                contents =
                  (try Ortac_runtime.Gospelstdlib.Sequence.empty
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "sequence_model.mli";
                                    pos_lnum = 6;
                                    pos_bol = 263;
                                    pos_cnum = 288
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "sequence_model.mli";
                                    pos_lnum = 6;
                                    pos_bol = 263;
                                    pos_cnum = 302
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__004_ 0) t_1__006_
      | Add v ->
          let t_2__007_ = Model.get state__004_ 0 in
          let t_2__008_ =
            let open ModelElt in
              {
                contents =
                  (try
                     Ortac_runtime.Gospelstdlib.Sequence.cons v
                       t_2__007_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "sequence_model.mli";
                                    pos_lnum = 11;
                                    pos_bol = 475;
                                    pos_cnum = 500
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "sequence_model.mli";
                                    pos_lnum = 11;
                                    pos_bol = 475;
                                    pos_cnum = 532
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__004_ 1) t_2__008_
      | Remove ->
          let t_3__009_ = Model.get state__004_ 0 in
          let t_3__011_ =
            let open ModelElt in
              {
                contents =
                  (try
                     match Ortac_runtime.Gospelstdlib.Sequence.length
                             t_3__009_.contents
                     with
                     | __x__010_ when
                         (=) __x__010_
                           (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                         -> Ortac_runtime.Gospelstdlib.Sequence.empty
                     | _ ->
                         Ortac_runtime.Gospelstdlib.Sequence.tl
                           t_3__009_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "sequence_model.mli";
                                    pos_lnum = 20;
                                    pos_bol = 953;
                                    pos_cnum = 978
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "sequence_model.mli";
                                    pos_lnum = 22;
                                    pos_bol = 1070;
                                    pos_cnum = 1131
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__004_ 1) t_3__011_
      | Remove_ ->
          let t_4__012_ = Model.get state__004_ 0 in
          let t_4__014_ =
            let open ModelElt in
              {
                contents =
                  (try
                     match length_opt t_4__012_.contents with
                     | Some __x__013_ when
                         (=) __x__013_
                           (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                         -> Ortac_runtime.Gospelstdlib.Sequence.empty
                     | _ ->
                         Ortac_runtime.Gospelstdlib.Sequence.tl
                           t_4__012_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "sequence_model.mli";
                                    pos_lnum = 27;
                                    pos_bol = 1337;
                                    pos_cnum = 1362
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "sequence_model.mli";
                                    pos_lnum = 29;
                                    pos_bol = 1454;
                                    pos_cnum = 1515
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__004_ 1) t_4__014_
    let precond cmd__022_ state__023_ =
      match cmd__022_ with
      | Create () -> true
      | Add v -> true
      | Remove -> true
      | Remove_ -> true
    let postcond _ _ _ = true
    let run cmd__024_ sut__025_ =
      match cmd__024_ with
      | Create () ->
          Res
            (sut,
              (let res__026_ = create () in
               (SUT.push sut__025_ res__026_; res__026_)))
      | Add v ->
          Res
            (unit,
              (let t_2__027_ = SUT.pop sut__025_ in
               let res__028_ = add v t_2__027_ in
               (SUT.push sut__025_ t_2__027_; res__028_)))
      | Remove ->
          Res
            ((option char),
              (let t_3__029_ = SUT.pop sut__025_ in
               let res__030_ = remove t_3__029_ in
               (SUT.push sut__025_ t_3__029_; res__030_)))
      | Remove_ ->
          Res
            ((option char),
              (let t_4__031_ = SUT.pop sut__025_ in
               let res__032_ = remove_ t_4__031_ in
               (SUT.push sut__025_ t_4__031_; res__032_)))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_show_cmd cmd__034_ state__035_ last__037_ res__036_ =
  let open Spec in
    let open STM in
      match (cmd__034_, res__036_) with
      | (Create (), Res ((SUT, _), t_1)) ->
          let lhs = if last__037_ then "r" else SUT.get_name state__035_ 0
          and shift = 1 in
          Format.asprintf "let %s = %s %a" lhs "create"
            (Util.Pp.pp_unit true) ()
      | (Add v, Res ((Unit, _), _)) ->
          let lhs = if last__037_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %a %s" lhs "add"
            (Util.Pp.pp_char true) v (SUT.get_name state__035_ (0 + shift))
      | (Remove, Res ((Option (Char), _), _)) ->
          let lhs = if last__037_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "remove"
            (SUT.get_name state__035_ (0 + shift))
      | (Remove_, Res ((Option (Char), _), _)) ->
          let lhs = if last__037_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "remove_"
            (SUT.get_name state__035_ (0 + shift))
      | _ -> assert false
let ortac_postcond cmd__015_ state__016_ res__017_ =
  let open Spec in
    let open STM in
      let new_state__018_ = lazy (next_state cmd__015_ state__016_) in
      match (cmd__015_, res__017_) with
      | (Create (), Res ((SUT, _), t_1)) -> None
      | (Add v, Res ((Unit, _), _)) -> None
      | (Remove, Res ((Option (Char), _), o)) -> None
      | (Remove_, Res ((Option (Char), _), o_1)) -> None
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Sequence_model STM tests" 1
        check_init_state ortac_show_cmd ortac_postcond])
