(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32-34-37-38"]
open Submodule.M
module Ortac_runtime = Ortac_runtime_qcheck_stm_sequential
module SUT =
  (Ortac_runtime.SUT.Make)(struct type sut = int t
                                  let init () = make 0 end)
module ModelElt =
  struct
    type nonrec elt = {
      value: int }
    let init =
      let a_1 = 0 in
      {
        value =
          (try a_1
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "submodule.mli";
                            pos_lnum = 7;
                            pos_bol = 241;
                            pos_cnum = 265
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "submodule.mli";
                            pos_lnum = 7;
                            pos_bol = 241;
                            pos_cnum = 266
                          }
                      })))
      }
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type _ ty +=  
      | SUT: SUT.elt ty 
    let sut = (SUT, (fun _ -> "<sut>"))
    type sut = SUT.t
    let init_sut = SUT.create 0
    type state = Model.t
    let init_state = Model.create 0 ()
    type raw_cmd =
      | Make of int 
    type flag =
      | Seq 
      | Dom 
    type flagged_cmd = {
      flag: flag ;
      raw_cmd: raw_cmd }
    let with_flag flag raw_cmd = { flag; raw_cmd }
    type cmd =
      | Make of int 
    let show_cmd cmd__005_ =
      match cmd__005_ with
      | Make a_1 -> Format.asprintf "%s %a" "make" (Util.Pp.pp_int true) a_1
    let cleanup _ = ()
    let gen_cmd _ =
      let open QCheck in
        let open Gen in
          oneof_weighted [(1, ((pure (fun a_1 -> Make a_1)) <*> nat_small))]
    let arb_cmd state__001_ =
      let open QCheck in make ~print:show_cmd (gen_cmd state__001_)
    let next_state cmd__006_ state__007_ =
      match cmd__006_ with
      | Make a_1 ->
          let t_1__009_ =
            let open ModelElt in
              {
                value =
                  (try a_1
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "submodule.mli";
                                    pos_lnum = 7;
                                    pos_bol = 241;
                                    pos_cnum = 265
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "submodule.mli";
                                    pos_lnum = 7;
                                    pos_bol = 241;
                                    pos_cnum = 266
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__007_ 0) t_1__009_
    let precond cmd__014_ state__015_ =
      match cmd__014_ with | Make a_1 -> true
    let postcond _ _ _ = true
    let run cmd__016_ sut__017_ =
      match cmd__016_ with
      | Make a_1 ->
          Res
            (sut,
              (let res__018_ = make a_1 in
               (SUT.push sut__017_ res__018_; res__018_)))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_show_cmd cmd__020_ models__021_ last__023_ res__022_ =
  let open Spec in
    let open STM in
      match (cmd__020_, res__022_) with
      | (Make a_1, Res ((SUT, _), t_1)) ->
          let lhs = if last__023_ then "r" else Model.get_name models__021_ 0
          and shift = 1 in
          Format.asprintf "let %s = %s %a" lhs "make" (Util.Pp.pp_int true)
            a_1
      | _ -> assert false
let ortac_postcond cmd__010_ state__011_ res__012_ =
  let open Spec in
    let open STM in
      let new_state__013_ = lazy (next_state cmd__010_ state__011_) in
      match (cmd__010_, res__012_) with
      | (Make a_1, Res ((SUT, _), t_1)) -> None
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Submodule STM tests" 0
        check_init_state ortac_show_cmd ortac_postcond])
