(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32-38"]
open Test_without_sut
module Ortac_runtime = Ortac_runtime_qcheck_stm
module SUT =
  (Ortac_runtime.SUT.Make)(struct type sut = int t
                                  let init () = make 16 0 end)
module ModelElt =
  struct
    type nonrec elt = {
      contents: int list }
    let init =
      let i = 16
      and a_1 = 0 in
      {
        contents =
          (try
             Ortac_runtime.Gospelstdlib.List.init
               (Ortac_runtime.Gospelstdlib.integer_of_int i) (fun j -> a_1)
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "test_without_sut.mli";
                            pos_lnum = 7;
                            pos_bol = 283;
                            pos_cnum = 308
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "test_without_sut.mli";
                            pos_lnum = 7;
                            pos_bol = 283;
                            pos_cnum = 332
                          }
                      })))
      }
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    module QCheck =
      struct
        include QCheck
        module Gen = struct include Gen
                            let int = small_signed_int end
      end
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type _ ty +=  
      | SUT: SUT.elt ty 
    let sut = (SUT, (fun _ -> "<sut>"))
    type sut = SUT.t
    let init_sut = SUT.create 0
    type state = Model.t
    let init_state = Model.create 0 ()
    type cmd =
      | Make of int * int 
      | Add of int * int 
    let show_cmd cmd__001_ =
      match cmd__001_ with
      | Make (i, a_1) ->
          Format.asprintf "protect (fun () -> %s %a %a)" "make"
            (Util.Pp.pp_int true) i (Util.Pp.pp_int true) a_1
      | Add (a_2, b) ->
          Format.asprintf "%s %a %a" "add" (Util.Pp.pp_int true) a_2
            (Util.Pp.pp_int true) b
    let shrink_cmd cmd__002_ =
      let open QCheck in
        let open Shrink in
          let open Iter in
            match cmd__002_ with
            | Make (i, a_1) ->
                (map (fun i -> Make (i, a_1)) (int i)) <+>
                  (map (fun a_1 -> Make (i, a_1)) (int a_1))
            | Add (a_2, b) ->
                (map (fun a_2 -> Add (a_2, b)) (int a_2)) <+>
                  (map (fun b -> Add (a_2, b)) (int b))
    let cleanup _ = ()
    let arb_cmd _ =
      let open QCheck in
        make ~print:show_cmd ~shrink:shrink_cmd
          (let open Gen in
             oneof
               [((pure (fun i -> fun a_1 -> Make (i, a_1))) <*>
                   small_signed_int)
                  <*> small_signed_int;
               ((pure (fun a_2 -> fun b -> Add (a_2, b))) <*> int) <*> int])
    let next_state cmd__003_ state__004_ =
      match cmd__003_ with
      | Make (i, a_1) ->
          if
            (try
               Ortac_runtime.Gospelstdlib.(>=)
                 (Ortac_runtime.Gospelstdlib.integer_of_int i)
                 (Ortac_runtime.Gospelstdlib.integer_of_int 0)
             with
             | e ->
                 raise
                   (Ortac_runtime.Partial_function
                      (e,
                        {
                          Ortac_runtime.start =
                            {
                              pos_fname = "test_without_sut.mli";
                              pos_lnum = 6;
                              pos_bol = 265;
                              pos_cnum = 276
                            };
                          Ortac_runtime.stop =
                            {
                              pos_fname = "test_without_sut.mli";
                              pos_lnum = 6;
                              pos_bol = 265;
                              pos_cnum = 282
                            }
                        })))
          then
            let t_1__006_ =
              let open ModelElt in
                {
                  contents =
                    (try
                       Ortac_runtime.Gospelstdlib.List.init
                         (Ortac_runtime.Gospelstdlib.integer_of_int i)
                         (fun j -> a_1)
                     with
                     | e ->
                         raise
                           (Ortac_runtime.Partial_function
                              (e,
                                {
                                  Ortac_runtime.start =
                                    {
                                      pos_fname = "test_without_sut.mli";
                                      pos_lnum = 7;
                                      pos_bol = 283;
                                      pos_cnum = 308
                                    };
                                  Ortac_runtime.stop =
                                    {
                                      pos_fname = "test_without_sut.mli";
                                      pos_lnum = 7;
                                      pos_bol = 283;
                                      pos_cnum = 332
                                    }
                                })))
                } in
            Model.push (Model.drop_n state__004_ 0) t_1__006_
          else state__004_
      | Add (a_2, b) -> state__004_
    let precond cmd__011_ state__012_ =
      match cmd__011_ with | Make (i, a_1) -> true | Add (a_2, b) -> true
    let postcond _ _ _ = true
    let run cmd__013_ sut__014_ =
      match cmd__013_ with
      | Make (i, a_1) ->
          Res
            ((result sut exn),
              (let res__015_ = protect (fun () -> make i a_1) () in
               ((match res__015_ with
                 | Ok res -> SUT.push sut__014_ res
                 | Error _ -> ());
                res__015_)))
      | Add (a_2, b) -> Res (int, (let res__016_ = add a_2 b in res__016_))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_show_cmd cmd__018_ state__019_ last__021_ res__020_ =
  let open Spec in
    let open STM in
      match (cmd__018_, res__020_) with
      | (Make (i, a_1), Res ((Result (SUT, Exn), _), t_1)) ->
          let lhs =
            if last__021_
            then "r"
            else
              (match t_1 with
               | Ok _ -> "Ok " ^ (SUT.get_name state__019_ 0)
               | Error _ -> "_")
          and shift = match t_1 with | Ok _ -> 1 | Error _ -> 0 in
          Format.asprintf "let %s = protect (fun () -> %s %a %a)" lhs "make"
            (Util.Pp.pp_int true) i (Util.Pp.pp_int true) a_1
      | (Add (a_2, b), Res ((Int, _), _)) ->
          let lhs = if last__021_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %a %a" lhs "add" (Util.Pp.pp_int true)
            a_2 (Util.Pp.pp_int true) b
      | _ -> assert false
let ortac_postcond cmd__007_ state__008_ res__009_ =
  let open Spec in
    let open STM in
      let new_state__010_ = lazy (next_state cmd__007_ state__008_) in
      match (cmd__007_, res__009_) with
      | (Make (i, a_1), Res ((Result (SUT, Exn), _), t_1)) ->
          (match if
                   try
                     Ortac_runtime.Gospelstdlib.(>=)
                       (Ortac_runtime.Gospelstdlib.integer_of_int i)
                       (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "test_without_sut.mli";
                                    pos_lnum = 6;
                                    pos_bol = 265;
                                    pos_cnum = 276
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "test_without_sut.mli";
                                    pos_lnum = 6;
                                    pos_bol = 265;
                                    pos_cnum = 282
                                  }
                              }))
                 then None
                 else
                   Some
                     (Ortac_runtime.report "Test_without_sut" "make 16 0"
                        (Ortac_runtime.Exception "Invalid_argument") "make"
                        [("i >= 0",
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "test_without_sut.mli";
                                 pos_lnum = 6;
                                 pos_bol = 265;
                                 pos_cnum = 276
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "test_without_sut.mli";
                                 pos_lnum = 6;
                                 pos_bol = 265;
                                 pos_cnum = 282
                               }
                           })])
           with
           | None -> (match t_1 with | Ok t_1 -> None | _ -> None)
           | _ ->
               (match t_1 with
                | Error (Invalid_argument _) -> None
                | _ ->
                    if
                      (try
                         Ortac_runtime.Gospelstdlib.(>=)
                           (Ortac_runtime.Gospelstdlib.integer_of_int i)
                           (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                       with
                       | e ->
                           raise
                             (Ortac_runtime.Partial_function
                                (e,
                                  {
                                    Ortac_runtime.start =
                                      {
                                        pos_fname = "test_without_sut.mli";
                                        pos_lnum = 6;
                                        pos_bol = 265;
                                        pos_cnum = 276
                                      };
                                    Ortac_runtime.stop =
                                      {
                                        pos_fname = "test_without_sut.mli";
                                        pos_lnum = 6;
                                        pos_bol = 265;
                                        pos_cnum = 282
                                      }
                                  })))
                    then None
                    else
                      Some
                        (Ortac_runtime.report "Test_without_sut" "make 16 0"
                           (Ortac_runtime.Exception "Invalid_argument")
                           "make"
                           [("i >= 0",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "test_without_sut.mli";
                                    pos_lnum = 6;
                                    pos_bol = 265;
                                    pos_cnum = 276
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "test_without_sut.mli";
                                    pos_lnum = 6;
                                    pos_bol = 265;
                                    pos_cnum = 282
                                  }
                              })])))
      | (Add (a_2, b), Res ((Int, _), c)) ->
          if
            (try
               (Ortac_runtime.Gospelstdlib.integer_of_int c) =
                 (Ortac_runtime.Gospelstdlib.(+)
                    (Ortac_runtime.Gospelstdlib.integer_of_int a_2)
                    (Ortac_runtime.Gospelstdlib.integer_of_int b))
             with
             | e ->
                 raise
                   (Ortac_runtime.Partial_function
                      (e,
                        {
                          Ortac_runtime.start =
                            {
                              pos_fname = "test_without_sut.mli";
                              pos_lnum = 11;
                              pos_bol = 499;
                              pos_cnum = 511
                            };
                          Ortac_runtime.stop =
                            {
                              pos_fname = "test_without_sut.mli";
                              pos_lnum = 11;
                              pos_bol = 499;
                              pos_cnum = 520
                            }
                        })))
          then None
          else
            Some
              (Ortac_runtime.report "Test_without_sut" "make 16 0"
                 (Ortac_runtime.Value
                    (Res
                       (integer,
                         (try
                            Ortac_runtime.Gospelstdlib.(+)
                              (Ortac_runtime.Gospelstdlib.integer_of_int a_2)
                              (Ortac_runtime.Gospelstdlib.integer_of_int b)
                          with
                          | e ->
                              raise
                                (Ortac_runtime.Partial_function
                                   (e,
                                     {
                                       Ortac_runtime.start =
                                         {
                                           pos_fname = "test_without_sut.mli";
                                           pos_lnum = 11;
                                           pos_bol = 499;
                                           pos_cnum = 517
                                         };
                                       Ortac_runtime.stop =
                                         {
                                           pos_fname = "test_without_sut.mli";
                                           pos_lnum = 11;
                                           pos_bol = 499;
                                           pos_cnum = 518
                                         }
                                     })))))) "add"
                 [("c = a + b",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "test_without_sut.mli";
                          pos_lnum = 11;
                          pos_bol = 499;
                          pos_cnum = 511
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "test_without_sut.mli";
                          pos_lnum = 11;
                          pos_bol = 499;
                          pos_cnum = 520
                        }
                    })])
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Test_without_sut STM tests" 0
        check_init_state ortac_show_cmd ortac_postcond])
