(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32-34-38"]
open Lwt_dllist_spec
module Ortac_runtime = Ortac_runtime_qcheck_stm_sequential
module SUT =
  (Ortac_runtime.SUT.Make)(struct type sut = int t
                                  let init () = create () end)
module ModelElt =
  struct
    type nonrec elt = {
      contents: int Ortac_runtime.Gospelstdlib.sequence }
    let init =
      let () = () in
      {
        contents =
          (try Ortac_runtime.Gospelstdlib.Sequence.empty
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "lwt_dllist_spec.mli";
                            pos_lnum = 46;
                            pos_bol = 1791;
                            pos_cnum = 1818
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "lwt_dllist_spec.mli";
                            pos_lnum = 46;
                            pos_bol = 1791;
                            pos_cnum = 1832
                          }
                      })))
      }
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    type _ ty +=  
      | Node: 'a ty -> 'a node ty 
    let node spec =
      let (ty, show) = spec in
      ((Node ty), (fun n -> Printf.sprintf "Node %s" (show (get n))))
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type _ ty +=  
      | SUT: SUT.elt ty 
    let sut = (SUT, (fun _ -> "<sut>"))
    type sut = SUT.t
    let init_sut = SUT.create 1
    type state = Model.t
    let init_state = Model.create 1 ()
    type cmd =
      | Create of unit 
      | Clear 
      | Is_empty 
      | Length 
      | Add_l of int 
      | Add_r of int 
      | Take_l 
      | Take_r 
      | Take_opt_l 
      | Take_opt_r 
    let show_cmd cmd__001_ =
      match cmd__001_ with
      | Create () ->
          Format.asprintf "%s %a" "create" (Util.Pp.pp_unit true) ()
      | Clear -> Format.asprintf "%s <sut>" "clear"
      | Is_empty -> Format.asprintf "%s <sut>" "is_empty"
      | Length -> Format.asprintf "%s <sut>" "length"
      | Add_l a_1 ->
          Format.asprintf "%s %a <sut>" "add_l" (Util.Pp.pp_int true) a_1
      | Add_r a_2 ->
          Format.asprintf "%s %a <sut>" "add_r" (Util.Pp.pp_int true) a_2
      | Take_l -> Format.asprintf "protect (fun () -> %s <sut>)" "take_l"
      | Take_r -> Format.asprintf "protect (fun () -> %s <sut>)" "take_r"
      | Take_opt_l -> Format.asprintf "%s <sut>" "take_opt_l"
      | Take_opt_r -> Format.asprintf "%s <sut>" "take_opt_r"
    let cleanup _ = ()
    let arb_cmd _ =
      let open QCheck in
        make ~print:show_cmd
          (let open Gen in
             oneof
               [(pure (fun () -> Create ())) <*> unit;
               pure Clear;
               pure Is_empty;
               pure Length;
               (pure (fun a_1 -> Add_l a_1)) <*> int;
               (pure (fun a_2 -> Add_r a_2)) <*> int;
               pure Take_l;
               pure Take_r;
               pure Take_opt_l;
               pure Take_opt_r])
    let next_state cmd__002_ state__003_ =
      match cmd__002_ with
      | Create () ->
          let s__005_ =
            let open ModelElt in
              {
                contents =
                  (try Ortac_runtime.Gospelstdlib.Sequence.empty
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 46;
                                    pos_bol = 1791;
                                    pos_cnum = 1818
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 46;
                                    pos_bol = 1791;
                                    pos_cnum = 1832
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 0) s__005_
      | Clear ->
          let s_1__006_ = Model.get state__003_ 0 in
          let s_1__007_ =
            let open ModelElt in
              {
                contents =
                  (try Ortac_runtime.Gospelstdlib.Sequence.empty
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 53;
                                    pos_bol = 2322;
                                    pos_cnum = 2349
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 53;
                                    pos_bol = 2322;
                                    pos_cnum = 2363
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) s_1__007_
      | Is_empty ->
          let s_2__008_ = Model.get state__003_ 0 in
          let s_2__009_ = s_2__008_ in
          Model.push (Model.drop_n state__003_ 1) s_2__009_
      | Length ->
          let s_3__010_ = Model.get state__003_ 0 in
          let s_3__011_ = s_3__010_ in
          Model.push (Model.drop_n state__003_ 1) s_3__011_
      | Add_l a_1 ->
          let s_4__012_ = Model.get state__003_ 0 in
          let s_4__013_ =
            let open ModelElt in
              {
                contents =
                  (try
                     Ortac_runtime.Gospelstdlib.Sequence.cons a_1
                       s_4__012_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 71;
                                    pos_bol = 3600;
                                    pos_cnum = 3627
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 71;
                                    pos_bol = 3600;
                                    pos_cnum = 3659
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) s_4__013_
      | Add_r a_2 ->
          let s_5__014_ = Model.get state__003_ 0 in
          let s_5__015_ =
            let open ModelElt in
              {
                contents =
                  (try
                     Ortac_runtime.Gospelstdlib.Sequence.snoc
                       s_5__014_.contents a_2
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 77;
                                    pos_bol = 4068;
                                    pos_cnum = 4095
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 77;
                                    pos_bol = 4068;
                                    pos_cnum = 4127
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) s_5__015_
      | Take_l ->
          let s_6__016_ = Model.get state__003_ 0 in
          let s_6__017_ =
            let open ModelElt in
              {
                contents =
                  (try
                     if
                       s_6__016_.contents =
                         Ortac_runtime.Gospelstdlib.Sequence.empty
                     then Ortac_runtime.Gospelstdlib.Sequence.empty
                     else
                       Ortac_runtime.Gospelstdlib.Sequence.tl
                         s_6__016_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 89;
                                    pos_bol = 4665;
                                    pos_cnum = 4692
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 91;
                                    pos_bol = 4774;
                                    pos_cnum = 4834
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) s_6__017_
      | Take_r ->
          let s_7__018_ = Model.get state__003_ 0 in
          let s_7__019_ =
            let open ModelElt in
              {
                contents =
                  (try
                     if
                       s_7__018_.contents =
                         Ortac_runtime.Gospelstdlib.Sequence.empty
                     then Ortac_runtime.Gospelstdlib.Sequence.empty
                     else
                       Ortac_runtime.Gospelstdlib.__mix_Bddub
                         s_7__018_.contents
                         (Ortac_runtime.Gospelstdlib.(-)
                            (Ortac_runtime.Gospelstdlib.Sequence.length
                               s_7__018_.contents)
                            (Ortac_runtime.Gospelstdlib.integer_of_int 2))
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 103;
                                    pos_bol = 5470;
                                    pos_cnum = 5497
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 105;
                                    pos_bol = 5579;
                                    pos_cnum = 5669
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) s_7__019_
      | Take_opt_l ->
          let s_8__020_ = Model.get state__003_ 0 in
          let s_8__021_ =
            let open ModelElt in
              {
                contents =
                  (try
                     if
                       (Ortac_runtime.Gospelstdlib.Sequence.length
                          s_8__020_.contents)
                         = (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                     then Ortac_runtime.Gospelstdlib.Sequence.empty
                     else
                       Ortac_runtime.Gospelstdlib.Sequence.tl
                         s_8__020_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 116;
                                    pos_bol = 6372;
                                    pos_cnum = 6399
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 118;
                                    pos_bol = 6486;
                                    pos_cnum = 6546
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) s_8__021_
      | Take_opt_r ->
          let s_9__022_ = Model.get state__003_ 0 in
          let s_9__024_ =
            let open ModelElt in
              {
                contents =
                  (try
                     match Ortac_runtime.Gospelstdlib.Sequence.length
                             s_9__022_.contents
                     with
                     | __x__023_ when
                         (=) __x__023_
                           (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                         -> Ortac_runtime.Gospelstdlib.Sequence.empty
                     | l ->
                         Ortac_runtime.Gospelstdlib.__mix_Bddub
                           s_9__022_.contents
                           (Ortac_runtime.Gospelstdlib.(-) l
                              (Ortac_runtime.Gospelstdlib.integer_of_int 2))
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 128;
                                    pos_bol = 7208;
                                    pos_cnum = 7235
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "lwt_dllist_spec.mli";
                                    pos_lnum = 130;
                                    pos_bol = 7327;
                                    pos_cnum = 7385
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) s_9__024_
    let precond cmd__062_ state__063_ =
      match cmd__062_ with
      | Create () -> true
      | Clear -> true
      | Is_empty -> true
      | Length -> true
      | Add_l a_1 -> true
      | Add_r a_2 -> true
      | Take_l -> true
      | Take_r -> true
      | Take_opt_l -> true
      | Take_opt_r -> true
    let postcond _ _ _ = true
    let run cmd__064_ sut__065_ =
      match cmd__064_ with
      | Create () ->
          Res
            (sut,
              (let res__066_ = create () in
               (SUT.push sut__065_ res__066_; res__066_)))
      | Clear ->
          Res
            (unit,
              (let s_1__067_ = SUT.get sut__065_ 0 in
               let res__068_ = clear s_1__067_ in res__068_))
      | Is_empty ->
          Res
            (bool,
              (let s_2__069_ = SUT.get sut__065_ 0 in
               let res__070_ = is_empty s_2__069_ in res__070_))
      | Length ->
          Res
            (int,
              (let s_3__071_ = SUT.get sut__065_ 0 in
               let res__072_ = length s_3__071_ in res__072_))
      | Add_l a_1 ->
          Res
            ((node int),
              (let s_4__073_ = SUT.get sut__065_ 0 in
               let res__074_ = add_l a_1 s_4__073_ in res__074_))
      | Add_r a_2 ->
          Res
            ((node int),
              (let s_5__075_ = SUT.get sut__065_ 0 in
               let res__076_ = add_r a_2 s_5__075_ in res__076_))
      | Take_l ->
          Res
            ((result int exn),
              (let s_6__077_ = SUT.get sut__065_ 0 in
               let res__078_ = protect (fun () -> take_l s_6__077_) () in
               res__078_))
      | Take_r ->
          Res
            ((result int exn),
              (let s_7__079_ = SUT.get sut__065_ 0 in
               let res__080_ = protect (fun () -> take_r s_7__079_) () in
               res__080_))
      | Take_opt_l ->
          Res
            ((option int),
              (let s_8__081_ = SUT.get sut__065_ 0 in
               let res__082_ = take_opt_l s_8__081_ in res__082_))
      | Take_opt_r ->
          Res
            ((option int),
              (let s_9__083_ = SUT.get sut__065_ 0 in
               let res__084_ = take_opt_r s_9__083_ in res__084_))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_show_cmd cmd__086_ state__087_ last__089_ res__088_ =
  let open Spec in
    let open STM in
      match (cmd__086_, res__088_) with
      | (Create (), Res ((SUT, _), s)) ->
          let lhs = if last__089_ then "r" else SUT.get_name state__087_ 0
          and shift = 1 in
          Format.asprintf "let %s = %s %a" lhs "create"
            (Util.Pp.pp_unit true) ()
      | (Clear, Res ((Unit, _), _)) ->
          let lhs = if last__089_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "clear"
            (SUT.get_name state__087_ (0 + shift))
      | (Is_empty, Res ((Bool, _), _)) ->
          let lhs = if last__089_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "is_empty"
            (SUT.get_name state__087_ (0 + shift))
      | (Length, Res ((Int, _), _)) ->
          let lhs = if last__089_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "length"
            (SUT.get_name state__087_ (0 + shift))
      | (Add_l a_1, Res ((Node (Int), _), _)) ->
          let lhs = if last__089_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %a %s" lhs "add_l"
            (Util.Pp.pp_int true) a_1 (SUT.get_name state__087_ (0 + shift))
      | (Add_r a_2, Res ((Node (Int), _), _)) ->
          let lhs = if last__089_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %a %s" lhs "add_r"
            (Util.Pp.pp_int true) a_2 (SUT.get_name state__087_ (0 + shift))
      | (Take_l, Res ((Result (Int, Exn), _), _)) ->
          let lhs = if last__089_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = protect (fun () -> %s %s)" lhs "take_l"
            (SUT.get_name state__087_ (0 + shift))
      | (Take_r, Res ((Result (Int, Exn), _), _)) ->
          let lhs = if last__089_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = protect (fun () -> %s %s)" lhs "take_r"
            (SUT.get_name state__087_ (0 + shift))
      | (Take_opt_l, Res ((Option (Int), _), _)) ->
          let lhs = if last__089_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "take_opt_l"
            (SUT.get_name state__087_ (0 + shift))
      | (Take_opt_r, Res ((Option (Int), _), _)) ->
          let lhs = if last__089_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "take_opt_r"
            (SUT.get_name state__087_ (0 + shift))
      | _ -> assert false
let ortac_postcond cmd__025_ state__026_ res__027_ =
  let open Spec in
    let open STM in
      let new_state__028_ = lazy (next_state cmd__025_ state__026_) in
      match (cmd__025_, res__027_) with
      | (Create (), Res ((SUT, _), s)) -> None
      | (Clear, Res ((Unit, _), _)) -> None
      | (Is_empty, Res ((Bool, _), b)) ->
          if
            let s_old__032_ = Model.get state__026_ 0
            and s_new__033_ = lazy (Model.get (Lazy.force new_state__028_) 0) in
            (try
               (b = true) =
                 ((Lazy.force s_new__033_).contents =
                    Ortac_runtime.Gospelstdlib.Sequence.empty)
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Lwt_dllist_spec" "create ()"
                 (try
                    Ortac_runtime.Report.Value
                      (Res
                         (bool,
                           (let s_old__030_ = Model.get state__026_ 0
                            and s_new__031_ =
                              lazy (Model.get (Lazy.force new_state__028_) 0) in
                            (Lazy.force s_new__031_).contents =
                              Ortac_runtime.Gospelstdlib.Sequence.empty)))
                  with | e -> Ortac_runtime.Report.Out_of_domain) "is_empty"
                 [("b <-> s.contents = Sequence.empty",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "lwt_dllist_spec.mli";
                          pos_lnum = 58;
                          pos_bol = 2709;
                          pos_cnum = 2723
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "lwt_dllist_spec.mli";
                          pos_lnum = 58;
                          pos_bol = 2709;
                          pos_cnum = 2756
                        }
                    })])
      | (Length, Res ((Int, _), l_1)) ->
          if
            let s_old__037_ = Model.get state__026_ 0
            and s_new__038_ = lazy (Model.get (Lazy.force new_state__028_) 0) in
            (try
               (Ortac_runtime.Gospelstdlib.integer_of_int l_1) =
                 (Ortac_runtime.Gospelstdlib.Sequence.length
                    (Lazy.force s_new__038_).contents)
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Lwt_dllist_spec" "create ()"
                 (try
                    Ortac_runtime.Report.Value
                      (Res
                         (integer,
                           (let s_old__035_ = Model.get state__026_ 0
                            and s_new__036_ =
                              lazy (Model.get (Lazy.force new_state__028_) 0) in
                            Ortac_runtime.Gospelstdlib.Sequence.length
                              (Lazy.force s_new__036_).contents)))
                  with | e -> Ortac_runtime.Report.Out_of_domain) "length"
                 [("l = Sequence.length s.contents",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "lwt_dllist_spec.mli";
                          pos_lnum = 65;
                          pos_bol = 3164;
                          pos_cnum = 3178
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "lwt_dllist_spec.mli";
                          pos_lnum = 65;
                          pos_bol = 3164;
                          pos_cnum = 3208
                        }
                    })])
      | (Add_l a_1, Res ((Node (Int), _), n)) -> None
      | (Add_r a_2, Res ((Node (Int), _), n_1)) -> None
      | (Take_l, Res ((Result (Int, Exn), _), a_3)) ->
          (match a_3 with
           | Ok a_3 ->
               if
                 let s_old__042_ = Model.get state__026_ 0
                 and s_new__043_ =
                   lazy (Model.get (Lazy.force new_state__028_) 0) in
                 (try
                    if
                      s_old__042_.contents =
                        Ortac_runtime.Gospelstdlib.Sequence.empty
                    then false
                    else
                      a_3 =
                        (Ortac_runtime.Gospelstdlib.Sequence.hd
                           s_old__042_.contents)
                  with | e -> false)
               then None
               else
                 Some
                   (Ortac_runtime.Report.report "Lwt_dllist_spec" "create ()"
                      (try
                         Ortac_runtime.Report.Protected_value
                           (Res (Ortac_runtime.Report.dummy, ()))
                       with | e -> Ortac_runtime.Report.Out_of_domain)
                      "take_l"
                      [("if old s.contents = Sequence.empty\n              then false\n              else a = Sequence.hd (old s.contents)",
                         {
                           Ortac_runtime.start =
                             {
                               pos_fname = "lwt_dllist_spec.mli";
                               pos_lnum = 92;
                               pos_bol = 4835;
                               pos_cnum = 4849
                             };
                           Ortac_runtime.stop =
                             {
                               pos_fname = "lwt_dllist_spec.mli";
                               pos_lnum = 94;
                               pos_bol = 4909;
                               pos_cnum = 4960
                             }
                         })])
           | Error (Empty) ->
               if
                 let s_old__044_ = Model.get state__026_ 0
                 and s_new__045_ =
                   lazy (Model.get (Lazy.force new_state__028_) 0) in
                 (try
                    let __t1__046_ =
                      s_old__044_.contents =
                        Ortac_runtime.Gospelstdlib.Sequence.empty in
                    let __t2__047_ =
                      Ortac_runtime.Gospelstdlib.Sequence.empty =
                        (Lazy.force s_new__045_).contents in
                    __t1__046_ && __t2__047_
                  with | e -> false)
               then None
               else
                 Some
                   (Ortac_runtime.Report.report "Lwt_dllist_spec" "create ()"
                      (try Ortac_runtime.Report.Exception "Empty"
                       with | e -> Ortac_runtime.Report.Out_of_domain)
                      "take_l"
                      [("old s.contents = Sequence.empty = s.contents",
                         {
                           Ortac_runtime.start =
                             {
                               pos_fname = "lwt_dllist_spec.mli";
                               pos_lnum = 95;
                               pos_bol = 4961;
                               pos_cnum = 4983
                             };
                           Ortac_runtime.stop =
                             {
                               pos_fname = "lwt_dllist_spec.mli";
                               pos_lnum = 95;
                               pos_bol = 4961;
                               pos_cnum = 5027
                             }
                         })])
           | _ -> None)
      | (Take_r, Res ((Result (Int, Exn), _), a_4)) ->
          (match a_4 with
           | Ok a_4 ->
               if
                 let s_old__049_ = Model.get state__026_ 0
                 and s_new__050_ =
                   lazy (Model.get (Lazy.force new_state__028_) 0) in
                 (try
                    if
                      s_old__049_.contents =
                        Ortac_runtime.Gospelstdlib.Sequence.empty
                    then false
                    else
                      a_4 =
                        (Ortac_runtime.Gospelstdlib.__mix_Bub
                           s_old__049_.contents
                           (Ortac_runtime.Gospelstdlib.(-)
                              (Ortac_runtime.Gospelstdlib.Sequence.length
                                 s_old__049_.contents)
                              (Ortac_runtime.Gospelstdlib.integer_of_int 1)))
                  with | e -> false)
               then None
               else
                 Some
                   (Ortac_runtime.Report.report "Lwt_dllist_spec" "create ()"
                      (try
                         Ortac_runtime.Report.Protected_value
                           (Res (Ortac_runtime.Report.dummy, ()))
                       with | e -> Ortac_runtime.Report.Out_of_domain)
                      "take_r"
                      [("if old s.contents = Sequence.empty\n              then false\n              else a = (old s.contents)[Sequence.length (old s.contents) - 1]",
                         {
                           Ortac_runtime.start =
                             {
                               pos_fname = "lwt_dllist_spec.mli";
                               pos_lnum = 106;
                               pos_bol = 5670;
                               pos_cnum = 5684
                             };
                           Ortac_runtime.stop =
                             {
                               pos_fname = "lwt_dllist_spec.mli";
                               pos_lnum = 108;
                               pos_bol = 5744;
                               pos_cnum = 5821
                             }
                         })])
           | Error (Empty) ->
               if
                 let s_old__051_ = Model.get state__026_ 0
                 and s_new__052_ =
                   lazy (Model.get (Lazy.force new_state__028_) 0) in
                 (try
                    let __t1__053_ =
                      s_old__051_.contents =
                        Ortac_runtime.Gospelstdlib.Sequence.empty in
                    let __t2__054_ =
                      Ortac_runtime.Gospelstdlib.Sequence.empty =
                        (Lazy.force s_new__052_).contents in
                    __t1__053_ && __t2__054_
                  with | e -> false)
               then None
               else
                 Some
                   (Ortac_runtime.Report.report "Lwt_dllist_spec" "create ()"
                      (try Ortac_runtime.Report.Exception "Empty"
                       with | e -> Ortac_runtime.Report.Out_of_domain)
                      "take_r"
                      [("old s.contents = Sequence.empty = s.contents",
                         {
                           Ortac_runtime.start =
                             {
                               pos_fname = "lwt_dllist_spec.mli";
                               pos_lnum = 109;
                               pos_bol = 5822;
                               pos_cnum = 5844
                             };
                           Ortac_runtime.stop =
                             {
                               pos_fname = "lwt_dllist_spec.mli";
                               pos_lnum = 109;
                               pos_bol = 5822;
                               pos_cnum = 5888
                             }
                         })])
           | _ -> None)
      | (Take_opt_l, Res ((Option (Int), _), o)) ->
          if
            let s_old__056_ = Model.get state__026_ 0
            and s_new__057_ = lazy (Model.get (Lazy.force new_state__028_) 0) in
            (try
               s_old__056_.contents =
                 (match o with
                  | None -> Ortac_runtime.Gospelstdlib.Sequence.empty
                  | Some a_5 ->
                      Ortac_runtime.Gospelstdlib.Sequence.cons a_5
                        (Lazy.force s_new__057_).contents)
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Lwt_dllist_spec" "create ()"
                 (try
                    Ortac_runtime.Report.Value
                      (Res (Ortac_runtime.Report.dummy, ()))
                  with | e -> Ortac_runtime.Report.Out_of_domain)
                 "take_opt_l"
                 [("old s.contents = match o with\n                                | None -> Sequence.empty\n                                | Some a -> Sequence.cons a s.contents",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "lwt_dllist_spec.mli";
                          pos_lnum = 119;
                          pos_bol = 6547;
                          pos_cnum = 6561
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "lwt_dllist_spec.mli";
                          pos_lnum = 121;
                          pos_bol = 6648;
                          pos_cnum = 6718
                        }
                    })])
      | (Take_opt_r, Res ((Option (Int), _), o_1)) ->
          if
            let s_old__059_ = Model.get state__026_ 0
            and s_new__060_ = lazy (Model.get (Lazy.force new_state__028_) 0) in
            (try
               s_old__059_.contents =
                 (match o_1 with
                  | None -> Ortac_runtime.Gospelstdlib.Sequence.empty
                  | Some a_6 ->
                      Ortac_runtime.Gospelstdlib.Sequence.snoc
                        (Lazy.force s_new__060_).contents a_6)
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Lwt_dllist_spec" "create ()"
                 (try
                    Ortac_runtime.Report.Value
                      (Res (Ortac_runtime.Report.dummy, ()))
                  with | e -> Ortac_runtime.Report.Out_of_domain)
                 "take_opt_r"
                 [("old s.contents = match o with\n                                | None -> Sequence.empty\n                                | Some a -> Sequence.snoc s.contents a",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "lwt_dllist_spec.mli";
                          pos_lnum = 131;
                          pos_bol = 7386;
                          pos_cnum = 7400
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "lwt_dllist_spec.mli";
                          pos_lnum = 133;
                          pos_bol = 7487;
                          pos_cnum = 7557
                        }
                    })])
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Lwt_dllist_spec STM tests" 1
        check_init_state ortac_show_cmd ortac_postcond])
